/* DỮ LIỆU SẢN PHẨM - TRẦN HỮU MINH */
const BRANDS = [
  { id:'munich', name:'Munich', icon:'⭐', color:'#e94560', desc:'Chống thấm & Sơn công nghiệp - Phân phối chính thức', count:0 },
  { id:'nano', name:'Nano House', icon:'🏡', color:'#0fb9b1', desc:'Sơn & Chống thấm công nghệ Nano - Phân phối chính thức', count:0 },
  { id:'sika', name:'Sika', icon:'🧪', color:'#6c5ce7', desc:'Vữa kỹ thuật & Chống thấm', count:0 },
  { id:'dulux', name:'Dulux', icon:'🎨', color:'#0984e3', desc:'Sơn nội thất & ngoại thất', count:0 },
  { id:'jotun', name:'Jotun', icon:'🖌️', color:'#f39c12', desc:'Sơn nội thất & ngoại thất cao cấp', count:0 },
  { id:'kova', name:'Kova', icon:'🏺', color:'#e17055', desc:'Chống thấm & Sơn nước', count:0 },
  { id:'nippon', name:'Nippon', icon:'🇯🇵', color:'#00b894', desc:'Sơn nội thất & ngoại thất', count:0 },
];

const PRODUCTS = {
  munich: {
    "🎨 Sơn nước": {
      "Nội thất": [
        { code:'Luxury Prime NT', name:'Sơn lót kháng kiềm nội thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn lót kháng kiềm cao cấp cho tường nội thất.', dm:'Theo hướng dẫn' },
        { code:'Luxury - Siêu bóng NT', name:'Sơn siêu bóng nội thất', spec:'Lon 5L / Thùng 18L', desc:'Công nghệ Polymer cao cấp, siêu bóng, dễ lau chùi.', dm:'2-3 lớp, cách nhau 1-2 giờ' },
        { code:'Fly - Bóng mờ NT', name:'Sơn bóng mờ cao cấp nội thất', spec:'Lon 5L / Thùng 18L', desc:'Bóng mờ sang trọng, phù hợp mọi không gian.', dm:'2-3 lớp, cách 5-6 giờ' },
        { code:'Action - Siêu mịn NT', name:'Sơn siêu mịn nội thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn mịn chất lượng cao, giá hợp lý.', dm:'2 lớp, cách 30-60 phút' },
        { code:'Nano AB', name:'Sơn diệt khuẩn 99,99% nội thất', spec:'Lon 5L / Thùng 18L', desc:'Công nghệ Nano bạc diệt khuẩn. Dùng cho bệnh viện, trường học, nhà máy thực phẩm.', dm:'Theo hướng dẫn' },
        { code:'Economy', name:'Sơn kinh tế nội thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn nội thất giá rẻ, chất lượng cơ bản.', dm:'Theo hướng dẫn' },
      ],
      "Ngoại thất": [
        { code:'Luxury Prime NT2', name:'Sơn lót kháng kiềm ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn lót kháng kiềm cho tường ngoài trời.', dm:'Theo hướng dẫn' },
        { code:'Luxury - Siêu bóng NT2', name:'Sơn siêu bóng ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Siêu bóng ngoại thất, chịu thời tiết khắc nghiệt.', dm:'2-3 lớp' },
        { code:'Fly - Bóng mờ NT2', name:'Sơn bóng mờ cao cấp ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Bóng mờ ngoại thất, chịu thời tiết tốt.', dm:'Theo hướng dẫn' },
        { code:'Action - Siêu mịn NT2', name:'Sơn siêu mịn ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn mịn ngoại thất chất lượng cao.', dm:'Theo hướng dẫn' },
      ],
    },
    "🛡️ Sơn chống thấm": {
      "Xi măng-polymer": [
        { code:'G20', name:'Màng chống thấm đàn hồi 200%', spec:'Bộ 26kg', desc:'Chống thấm hai thành phần xi măng-polymer siêu đàn hồi.', dm:'0,6 kg/m², 2-3 lớp' },
        { code:'G20S', name:'Màng chống thấm đàn hồi 200%', spec:'Bộ 25kg', desc:'Giống G20, quy cách khác.', dm:'0,6 kg/m², 2-3 lớp' },
        { code:'G20C', name:'Siêu cứng, hiệu ứng lá sen', spec:'Bộ 20kg', desc:'Chống thấm cao cấp hiệu ứng lá sen.', dm:'0,6-1 kg/m²/lớp' },
        { code:'G20C-Đen', name:'Chống thấm màu đen bể cá Koi', spec:'Bộ 20kg', desc:'Chuyên cho bể cá Koi, an toàn cho sinh vật.', dm:'0,6-1 kg/m²/lớp' },
        { code:'C20', name:'Màng chống thấm siêu cứng', spec:'Thùng 20kg', desc:'Lót cho PU S700, S400, chống thấm tường ngoài.', dm:'0,6-1 kg/m²/lớp' },
      ],
      "Acrylic": [
        { code:'CT0', name:'Acrylic chống thấm pha xi măng', spec:'Lon 5kg / Thùng 18kg', desc:'Chống thấm sàn mái, ban công, tường ngoài.', dm:'1kg + 0,5kg xi măng + 0,3kg nước' },
      ],
      "Polyurethane (PU)": [
        { code:'PU S700', name:'Chống thấm PU 1 TP (gốc nước) - đàn hồi 700%', spec:'Lon 1L/4L / Thùng 18L', desc:'Chống thấm lộ thiên, chịu UV. Hơn 1.000 màu.', dm:'0,75 kg/m²/lớp' },
        { code:'PU S400', name:'Chống thấm PU 1 TP (gốc nước) - đàn hồi 400%', spec:'Lon 5L / Thùng 18L', desc:'Giống S700, giá hợp lý hơn.', dm:'~6 m²/lớp' },
        { code:'PU S800F', name:'Chống thấm PU 2 TP (gốc dầu) - đàn hồi 700%', spec:'Bộ 3,6kg/18kg', desc:'Chống thấm lộ thiên, cần lót EP11.', dm:'1 kg/m²' },
        { code:'Pu Glass', name:'Chống thấm PU trong suốt - đàn hồi 600%', spec:'Lon 1L/4L / Thùng 18L', desc:'Màng chống thấm trong suốt 1 TP gốc nước.', dm:'0,75 kg/m²/lớp' },
      ],
      "Bitum & Đặc chủng": [
        { code:'G10', name:'Chống thấm Bitum-Polymer', spec:'Thùng 18kg / Lon 3,5kg', desc:'Chống thấm mái bằng, tầng hầm, WC.', dm:'Lót 0,2-0,3; Phủ 0,6 kg/m²/lớp' },
        { code:'G68', name:'Bitum nhựa đường biến tính', spec:'Thùng 18kg', desc:'Lớp lót cho màng khò Bitum.', dm:'Theo hướng dẫn' },
        { code:'S902', name:'Sơn sàn PU kho lạnh', spec:'Bộ 5kg/25kg', desc:'Chịu sốc nhiệt, chịu UV.', dm:'1 kg/m²/2 lớp' },
      ],
    },
    "🏭 Sơn công nghiệp": {
      "Epoxy": [
        { code:'EP11 Lót', name:'Sơn lót Epoxy gốc dung môi', spec:'Bộ 15kg/3kg', desc:'Lót cho sơn Epoxy và PU.', dm:'~100 m²/lớp' },
        { code:'EP11 Phủ', name:'Sơn phủ Epoxy hệ lăn', spec:'Bộ 15kg/3kg', desc:'Sơn phủ Epoxy cho sàn nhà xưởng.', dm:'~100 m²/lớp' },
        { code:'EP11 Tự san', name:'Sơn Epoxy tự san phẳng', spec:'Bộ 25kg/5kg', desc:'Tự san phẳng, dày ≥2mm.', dm:'1 kg/m²/dày 1mm' },
        { code:'EP12 Lót', name:'Sơn lót Epoxy gốc nước', spec:'Bộ 25kg/5kg', desc:'Không độc, không mùi.', dm:'~150 m²/lớp' },
        { code:'EP12 Phủ', name:'Sơn phủ Epoxy gốc nước', spec:'Bộ 25kg/5kg', desc:'Thân thiện môi trường.', dm:'~150 m²/lớp' },
      ],
      "Chống nóng & Thể thao": [
        { code:'UV20', name:'Sơn chống nóng cách nhiệt', spec:'Thùng 4L/18L', desc:'Giảm 5-28°C bề mặt mái.', dm:'Theo hướng dẫn' },
        { code:'UV20 Primer', name:'Lót chống nóng cho tôn cũ', spec:'Thùng 4L/18L', desc:'Lớp lót cho mái tôn cũ.', dm:'Theo hướng dẫn' },
        { code:'S632', name:'Sơn sân chơi thể thao', spec:'Lon 5L / Thùng 18L', desc:'Sơn trắng cho sân thể thao.', dm:'Theo hướng dẫn' },
      ],
    },
    "🔧 Phụ gia & VLXD": {
      "Phụ gia chống thấm": [
        { code:'Latex S', name:'Phụ gia kết nối chống thấm', spec:'Can 5kg/25kg', desc:'Làm hồ dầu, vữa trát chống thấm.', dm:'Theo hướng dẫn' },
        { code:'S208', name:'Phụ gia trộn vữa chống thấm', spec:'Túi 1kg', desc:'4-7 bao xi măng.', dm:'Theo hướng dẫn' },
        { code:'S302', name:'Phụ gia trộn vữa chống co ngót', spec:'Túi 1kg', desc:'Chống co ngót, tăng bám dính.', dm:'Theo hướng dẫn' },
        { code:'Walling', name:'Chống thấm tinh thể thẩm thấu (nước)', spec:'Chai 1L / Can 5L/25L', desc:'Chống muối hóa cho gạch, ngói, bê tông.', dm:'2-3 m²/lớp' },
        { code:'Stone SF', name:'Chống thấm tinh thể thẩm thấu (dầu)', spec:'Lon 1L/4L / Thùng 18L', desc:'Không lăn sơn nước lên trên được.', dm:'1-10 m²/lớp' },
        { code:'Kyton K101', name:'Chống thấm tinh thể dạng bột', spec:'Bao 20kg', desc:'Chống thấm thuận và nghịch.', dm:'2-5 kg/m²' },
        { code:'Water Plug', name:'Vật liệu đông cứng nhanh', spec:'Túi 1kg', desc:'Bịt kín lỗ rò rỉ nước tức thời.', dm:'Tức thời' },
      ],
      "Vữa & Keo dán": [
        { code:'Grout G650', name:'Vữa rót tự chảy không co ngót', spec:'Bao 25kg / Túi 4kg', desc:'Đổ cổ ống, hộp kỹ thuật.', dm:'1 m³ = 76 bao' },
        { code:'Repair G50', name:'Vữa sửa chữa bê tông', spec:'Bao 25kg', desc:'Sửa chữa bê tông hư hỏng.', dm:'10 m²/3 lớp' },
        { code:'Gel G-01', name:'Keo dán gạch đá', spec:'Bao 25kg', desc:'C1/C2/C3 tùy kích thước gạch.', dm:'Theo hướng dẫn' },
        { code:'Tile G07', name:'Keo chà ron miết mạch', spec:'Túi 1kg', desc:'Nhiều màu sắc.', dm:'1kg + 0,3L nước' },
        { code:'HF', name:'Bột rắc tăng cứng sàn', spec:'Bao 25kg', desc:'Tăng cứng sàn, chống mài mòn.', dm:'Theo hướng dẫn' },
      ],
    },
  },
  nano: {
    "Sơn phủ nội thất": [
      { code:'NO1', name:'SUPER INTERIOR - Sơn siêu bóng nội thất thượng hạng', spec:'15L / 5L / 1L', desc:'Bóng ngọc trai, bền màu gấp 3 lần, lau chùi hiệu quả, kháng khuẩn, chống nấm mốc. Sơn sinh thái eco, không APO, phooc môn, kim loại nặng.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO2', name:'ECO NANO GUARD - Sơn bóng nội thất cao cấp', spec:'18L / 5L', desc:'Công nghệ nano, màng sơn bóng công nghệ mới, lau chùi hiệu quả, kháng khuẩn, chống nấm mốc, an toàn sức khỏe.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO3', name:'ECO NANO GLOSSY - Sơn bóng nội thất cao cấp', spec:'18L / 5L', desc:'Công nghệ nano, lau chùi hiệu quả, kháng khuẩn, chống nấm mốc, màu sắc sắc nét, thân thiện môi trường.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO4', name:'ECO NANO CLEAN - Sơn bóng nội thất đặc biệt', spec:'18L / 5L', desc:'Công nghệ nano, lau chùi hiệu quả, chống nấm mốc, màu sắc sắc nét, thân thiện môi trường.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO5', name:'ECO CLASSIC - Sơn mịn nội thất cao cấp', spec:'18L / 5L', desc:'Màng sơn mịn, dễ lau chùi, không chì, thủy ngân, kim loại nặng, chống nấm mốc.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO6', name:'ECO SUPER WHITE - Sơn siêu trắng trần', spec:'18L / 5L', desc:'Siêu trắng sáng, chống nấm mốc hiệu quả, độ phủ cao.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO7', name:'ECO REGULAR - Sơn nội – ngoại thất đặc biệt', spec:'18L / 5L', desc:'Màng sơn mờ, độ phủ cao, dễ thi công, màu sắc đẹp và đa dạng.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
    "Sơn phủ ngoại thất": [
      { code:'NA1', name:'SUPER EXTERIOR - Sơn siêu bóng ngoại thất thượng hạng', spec:'5L / 1L', desc:'Chống bám bụi, bền màu gấp 5 lần, giảm nhiệt chống nóng, chống thấm, chống nấm mốc, kháng tia UV, cọ rửa tối đa. Sơn sinh thái eco.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA2', name:'ECO PRIMER EX - Sơn siêu bóng ngoại chống nóng cao cấp', spec:'15L / 5L / 1L', desc:'Chống bám bụi bền màu gấp 3 lần, giảm nhiệt chống nóng hiệu quả, chống thấm, chống nấm mốc, kháng tia UV. Sơn sinh thái eco.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA3', name:'ECO NANO SHIELD - Sơn bóng ngoại thất cao cấp', spec:'15L / 5L', desc:'Lau chùi hiệu quả, màng sơn tự làm sạch, chống thấm, chống rong rêu nấm mốc, an toàn sức khỏe.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA4', name:'ECO PLATIUM - Sơn mịn ngoại thất cao cấp', spec:'18L / 5L', desc:'Màu sắc rực rỡ, dễ lau chùi, bền màu, kháng khuẩn, màng sơn láng mịn, chịu thời tiết khắc nghiệt.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA5', name:'ECO CLEAR - Sơn siêu bóng ngoại chống nóng cao cấp', spec:'5L / 1L', desc:'Phủ bóng trong suốt, lau chùi hiệu quả tối đa, màng bóng đẹp trang trí và bảo vệ màng sơn trong.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA6', name:'ECO PROGUARD - Sơn chống thấm cao cấp', spec:'18L / 5L', desc:'Chống thấm cho sàn, mái, tường đứng, khu WC. Tăng tuổi thọ công trình.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA7', name:'ECO PROGUARD MÀU - Sơn chống thấm màu cao cấp', spec:'18L / 5L', desc:'Chống thấm đa màu Acrylic kết hợp silicone gốc nước, chống thấm tối ưu, màu bền đẹp.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
    "Sơn lót chống kiềm": [
      { code:'KT1', name:'ECO SEALER - Sơn lót kiềm nội – ngoại thất', spec:'18L / 5L', desc:'Chống kiềm hóa, chống rêu mốc, bảo vệ lớp sơn phủ.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KT2', name:'ECO SEALER - Sơn lót kiềm nội thất đặc biệt', spec:'18L / 5L', desc:'Chống kiềm hóa, chống rêu mốc, độ phủ cao, chống phai màu, bảo vệ lớp sơn phủ.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KT3', name:'INTERIOR - Sơn lót kiềm nội thất cao cấp', spec:'18L / 5L', desc:'Chống kiềm hoàn hảo, độ phủ cao, chống rêu mốc, tăng bám dính, bảo vệ lớp sơn màu.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KN1', name:'EX-MASTER - Sơn lót kiềm ngoại thất đặc biệt', spec:'18L / 5L', desc:'Chống kiềm và muối hóa hoàn hảo, chống rêu mốc, tăng gấp 2 bám dính cho sơn màu.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KN2', name:'EX-TERIOR - Sơn lót kiềm ngoại thất cao cấp', spec:'18L / 5L', desc:'Chống kiềm và muối hóa hoàn hảo, độ phủ cao, chống rêu mốc, tăng gấp 2 bám dính.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KN3', name:'ECO PRIMER - Sơn lót kiềm ngoại thất thượng hạng', spec:'18L / 5L', desc:'Siêu chống kiềm, chống muối hóa hoàn hảo, độ phủ cao, chống rêu mốc, bảo vệ màu, tăng gấp 2 bám dính.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
    "Bột bả": [
      { code:'B1', name:'HOME COAT - Bột bả trong và ngoài cao cấp', spec:'40kg', desc:'Bột bả trong và ngoài cao cấp.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'B2', name:'LEVEN COAT - Bột bả chống thấm cao cấp', spec:'40kg', desc:'Bột bả chống thấm cao cấp.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
  },
  sika: {
    "🧪 Chống thấm & Vữa": [
      { code:'Sika Top 107', name:'Vữa sửa chữa bê tông', spec:'Bao 25kg', desc:'Vữa gốc xi măng polymer. Sửa chữa bê tông hư hỏng, trám vá.', dm:'~2 kg/m²' },
      { code:'Sikalastic 1K', name:'Màng chống thấm lỏng PU một thành phần', spec:'Thùng 20kg', desc:'Màng chống thấm gốc PU, đàn hồi cao, chịu UV.', dm:'1 kg/m²/lớp' },
      { code:'Sika Latex', name:'Phụ gia chống thấm', spec:'Can 5L/25L', desc:'Phụ gia trộn vữa chống thấm, tăng kết dính, chống thấm.', dm:'0,5L/bao xi măng' },
      { code:'SikaGrout 214', name:'Vữa rót tự chảy không co ngót', spec:'Bao 25kg', desc:'Rót móng máy, neo bulon. Cường độ cao, không co ngót.', dm:'~1 m²/25kg' },
    ],
    "🔧 Keo & Phụ kiện": [
      { code:'Sikaflex 11FC', name:'Keo trám khe đa năng', spec:'Ống 600ml', desc:'Keo PU trám khe co giãn, chịu thời tiết khắc nghiệt.', dm:'Theo khe hở' },
    ],
  },
  dulux: {
    "🛡️ Ngoại thất siêu cao cấp": {
      "Weathershield Royal Shine": [
        { code:'WS-RoyalShine', name:'Weathershield Royal Shine - Chống vệt bẩn, chống bám bụi', spec:'1L / 5L', desc:'Chống vệt bẩn, chống bám bụi, chống rêu mốc mạnh gấp 3 lần. Chống kiềm hóa, chống phai màu. Bảo vệ màng sơn 12 năm.', dm:'Theo hướng dẫn' },
      ],
      "Weathershield Powerflexx": [
        { code:'WS-Powerflexx', name:'Weathershield Powerflexx - Màng co giãn gấp 6 lần', spec:'1L / 5L', desc:'Màng sơn co giãn gấp 6 lần, chống rạn nứt, chống thấm vượt trội, chống kiềm hóa, chống phai màu, chống rêu mốc.', dm:'Theo hướng dẫn' },
      ],
    },
    "🛡️ Ngoại thất cao cấp": {
      "Weathershield": [
        { code:'WS-CaoCap', name:'Weathershield Cao cấp - Chống rêu mốc, chống phai màu', spec:'1L / 5L / 15L', desc:'Chống rêu mốc dài lâu gấp 2 lần. Chống kiềm hóa, chống phai màu, chống bám bẩn, chống thấm.', dm:'Theo hướng dẫn' },
      ],
      "Weathershield Colour": [
        { code:'WS-Colour', name:'Weathershield Colour - Chống phai màu vượt trội', spec:'15L', desc:'Chống phai màu vượt trội, chống kiềm hóa, chống thấm, chống bám bẩn, chống rêu mốc.', dm:'Theo hướng dẫn' },
      ],
      "Inspire Ngoại thất": [
        { code:'IN-NgoaiThat-Bong', name:'Inspire Ngoại thất Bóng', spec:'5L', desc:'Màng sơn bền chắc, chống rêu mốc, chống bong tróc, bề mặt láng mịn, che phủ tốt.', dm:'Theo hướng dẫn' },
        { code:'IN-NgoaiThat-Mo', name:'Inspire Ngoại thất Mờ', spec:'5L / 15L / 18L', desc:'Màng sơn bền chắc, chống rêu mốc, bề mặt láng mịn, che phủ tốt.', dm:'Theo hướng dẫn' },
      ],
    },
    "🎨 Nội thất siêu cao cấp": {
      "Ambiance Breathing": [
        { code:'AM-Breathing', name:'Ambiance Breathing - Sơn sinh học 22% gốc sinh học', spec:'5L', desc:'22% thành phần gốc sinh học (than tre hoạt tính). Vô hiệu hóa formaldehyde, benzene, VOC. Bảo vệ sức khỏe.', dm:'Theo hướng dẫn' },
      ],
      "Ambiance 5in1 Superflexx": [
        { code:'AM-5in1-SieuBong', name:'Ambiance 5in1 Superflexx Siêu Bóng', spec:'1L / 3L', desc:'Màng sơn co giãn gấp 3 lần che lấp khe nứt nhỏ. Kháng khuẩn, ngăn ngừa nấm mốc.', dm:'Theo hướng dẫn' },
        { code:'AM-5in1-BongMo', name:'Ambiance 5in1 Superflexx Bóng Mờ', spec:'1L / 3L / 5L / 8L', desc:'Giải pháp toàn diện về trang trí và bảo vệ.', dm:'Theo hướng dẫn' },
      ],
      "Ambiance 5in1 Diamond Glow": [
        { code:'AM-DiamondGlow', name:'Ambiance 5in1 Diamond Glow Siêu Bóng', spec:'1L / 5L', desc:'Màu sắc rực rỡ, sắc nét, bền màu. Bề mặt láng mịn tuyệt hảo.', dm:'Theo hướng dẫn' },
      ],
    },
    "🎨 Nội thất cao cấp": {
      "EasyClean Chống Bám Bẩn": [
        { code:'EC-ChongBan-Bong', name:'EasyClean Chống Bám Bẩn Kháng Virus (Bóng)', spec:'1L / 5L / 15L', desc:'Kháng Virus & vi khuẩn. Chủ động chống bám bẩn, lau chùi cực hiệu quả. Bề mặt láng mịn, ngăn ngừa nấm mốc.', dm:'Theo hướng dẫn' },
        { code:'EC-ChongBan-Mo', name:'EasyClean Chống Bám Bẩn Kháng Virus (Mờ)', spec:'1L / 5L / 15L', desc:'Kháng Virus. Chống bám bẩn, lau chùi hiệu quả. Bề mặt mờ sang trọng.', dm:'Theo hướng dẫn' },
      ],
      "EasyClean Lau Chùi Vượt Trội": [
        { code:'EC-LauChuiVT-Bong', name:'EasyClean Lau Chùi Vượt Trội Kháng Virus (Bóng)', spec:'1L / 5L / 15L', desc:'Kháng Virus, lau chùi vượt trội, kháng khuẩn. Công nghệ Colourguard bảo vệ màng sơn.', dm:'Theo hướng dẫn' },
        { code:'EC-LauChuiVT-Mo', name:'EasyClean Lau Chùi Vượt Trội Kháng Virus (Mờ)', spec:'5L / 15L', desc:'Kháng Virus, lau chùi vượt trội. Bề mặt mờ.', dm:'Theo hướng dẫn' },
      ],
      "Inspire Nội thất MỚI": [
        { code:'IN-NoiThat-Bong-Moi', name:'Inspire Bóng (Mới) - ChromaBrite', spec:'5L', desc:'Công nghệ ChromaBrite giữ màu sắc bền và tươi đẹp. Dễ lau sạch vết bẩn. Chống vi khuẩn & nấm mốc.', dm:'Theo hướng dẫn' },
        { code:'IN-NoiThat-Mo-Moi', name:'Inspire Bóng Mờ (Mới)', spec:'5L', desc:'Công nghệ ChromaBrite. Dễ lau sạch vết bẩn. Chống vi khuẩn & nấm mốc.', dm:'Theo hướng dẫn' },
      ],
    },
    "🎨 Nội thất kinh tế": {
      "EasyClean Lau Chùi Hiệu Quả": [
        { code:'EC-LauChuiHQ-Bong', name:'EasyClean Lau Chùi Hiệu Quả (Bóng)', spec:'1L / 5L / 15L / 18L', desc:'Lau chùi, kháng khuẩn. Công nghệ Colourguard. Bề mặt láng mịn, ngăn ngừa nấm mốc.', dm:'Theo hướng dẫn' },
        { code:'EC-LauChuiHQ-Mo', name:'EasyClean Lau Chùi Hiệu Quả (Mờ)', spec:'1L / 5L / 15L / 18L', desc:'Lau chùi hiệu quả. Công nghệ Colourguard. Bề mặt mờ.', dm:'Theo hướng dẫn' },
      ],
    },
    "🧱 Sơn lót nội thất": [
      { code:'Supersealer', name:'Supersealer - Sơn lót nội thất', spec:'5L / 18L', desc:'Độ bám dính cao, tạo độ nhẵn mịn, chống kiềm, lấp lỗ kim.', dm:'Theo hướng dẫn' },
      { code:'AM-Primer', name:'Ambiance Primer - Lót nội thất cao cấp', spec:'5L / 18L', desc:'Tương thích dòng Ambiance. Bám dính cao, che phủ cao, tăng độ láng mịn.', dm:'Theo hướng dẫn' },
      { code:'IN-Primer', name:'Interior Primer - Lót nội thất', spec:'5L / 18L', desc:'Độ bám dính cao, tăng độ bền màu cho lớp phủ.', dm:'Theo hướng dẫn' },
      { code:'EC-Primer', name:'EasyClean Primer - Lót nội thất', spec:'5L / 15L', desc:'Tương thích dòng EasyClean & Inspire. Bám dính cực tốt.', dm:'Theo hướng dẫn' },
    ],
    "💧 Chống thấm Dulux": [
      { code:'Aquatech-Max', name:'Aquatech Max - Chống thấm sàn thế hệ mới', spec:'5kg / 20kg', desc:'Chống thấm gấp 2 lần. Màng chống thấm dày, co giãn cao, che lấp khe nứt. Không cần pha xi măng.', dm:'Theo hướng dẫn' },
      { code:'Aquatech-Flex', name:'Aquatech Flex - Chống thấm tường thế hệ mới', spec:'6kg / 20kg', desc:'Chống thấm gấp 2 lần. Màng dày, co giãn cao. Không cần pha xi măng.', dm:'Theo hướng dẫn' },
      { code:'Aquatech-VuotTroi', name:'Aquatech Chống thấm Vượt trội', spec:'6kg / 20kg', desc:'Bề mặt dai chắc, bám dính cao, bề mặt sáng đẹp. Pha trộn với xi măng.', dm:'Theo hướng dẫn' },
      { code:'Aquatech-BaoVe', name:'Chống thấm Bảo vệ Cao cấp', spec:'6kg / 20kg', desc:'Chống loang màu do kiềm hóa. Che phủ vết nứt. Không cần pha xi măng.', dm:'Theo hướng dẫn' },
    ],
    "🧱 Bột trét Dulux": [
      { code:'Botret-IN-EX', name:'Bột trét Nội & Ngoại thất', spec:'40kg', desc:'Tạo bề mặt láng mịn, độ bám dính cao.', dm:'Theo hướng dẫn' },
      { code:'Botret-IN', name:'Bột trét Nội thất', spec:'40kg', desc:'Tạo bề mặt láng mịn, độ bám dính cao, dễ thi công.', dm:'Theo hướng dẫn' },
    ],
    "🪵 Gỗ & Kim loại": [
      { code:'SonDau-Maxilite', name:'Sơn Dầu Maxilite cho Gỗ & Kim Loại', spec:'0.75L / 2.5L / 17L', desc:'Bề mặt bóng mịn, nhanh khô, độ phủ cao. Hơn 1.000 màu. Không chì, không thủy ngân.', dm:'Theo hướng dẫn' },
      { code:'Lot-ChongRi', name:'Sơn lót ngăn ngừa rỉ sét Maxilite', spec:'0.8L / 3L', desc:'Ngăn ngừa rỉ sét cho kim loại sắt thép. Tạo bám dính cho lớp hoàn thiện.', dm:'Theo hướng dẫn' },
    ],
  },
  jotun: {
    "🎨 Sơn nội thất": {
      "Majestic": [
        { code:'MJ-NguyenBan', name:'Majestic Đẹp Nguyên Bản - Siêu mờ, siêu bền', spec:'1L / 5L', desc:'Sơn nội thất đẹp nhất từ Jotun: mờ & siêu cao cấp, màu sắc trung thực, không phản quang, siêu bền, lau chùi vượt trội, kháng khuẩn, chống nấm mốc, rất nhẹ mùi.', dm:'Theo hướng dẫn' },
        { code:'MJ-HoanHao-Bong5', name:'Majestic Đẹp Hoàn Hảo Bóng 5%', spec:'1L / 5L / 15L', desc:'Cải tiến vượt trội về bề mặt nhăn mịn và khả năng dễ lau chùi, màu sắc rực rỡ, bền màu, kháng khuẩn, chống nấm mốc.', dm:'Theo hướng dẫn' },
        { code:'MJ-HoanHao-Mo', name:'Majestic Đẹp Hoàn Hảo Mờ', spec:'1L / 5L / 15L', desc:'Cải tiến vượt trội về bề mặt nhăn mịn và khả năng dễ lau chùi, màu sắc rực rỡ, bền màu, kháng khuẩn, chống nấm mốc, nhẹ mùi.', dm:'Theo hướng dẫn' },
      ],
      "Essence": [
        { code:'ES-ChePhu-Bong', name:'Essence Che Phủ Tối Đa Bóng', spec:'1L / 5L / 15L', desc:'Che phủ tối đa, bề mặt láng mịn, dễ lau chùi, chống nấm mốc, VOC thấp, nhẹ mùi, dễ thi công.', dm:'Theo hướng dẫn' },
        { code:'ES-ChePhu-Mo', name:'Essence Che Phủ Tối Đa Mờ', spec:'1L / 5L / 15L', desc:'Che phủ tối đa, bề mặt láng mịn, dễ lau chùi, chống nấm mốc, VOC thấp, nhẹ mùi, dễ thi công.', dm:'Theo hướng dẫn' },
        { code:'ES-SonTrangTran', name:'Essence Sơn Trắng Trần Chuyên Dụng', spec:'3L / 17L', desc:'Chống văng bắn, che phủ tốt, siêu trắng, dễ thi công, chống nấm mốc, VOC thấp, nhẹ mùi.', dm:'Theo hướng dẫn' },
        { code:'ES-DeLauChui', name:'Essence Dễ Lau Chùi', spec:'1L / 5L / 17L', desc:'Dễ lau chùi, nhẹ mùi, chống nấm mốc, VOC thấp, dễ thi công, độ che phủ cao.', dm:'Theo hướng dẫn' },
      ],
      "Jotaplast": [
        { code:'Jotaplast', name:'Jotaplast - Sơn kinh tế', spec:'5L', desc:'Màu tiêu chuẩn và siêu trắng, màng sơn mờ, chống nấm mốc, độ phủ cao, dễ thi công, hiệu quả kinh tế.', dm:'Theo hướng dẫn' },
      ],
    },
    "🛡️ Sơn ngoại thất": {
      "Jotashield": [
        { code:'JS-BenMauToanDien', name:'Jotashield Bền Màu Toàn Diện', spec:'1L / 5L / 15L', desc:'Bảo vệ bền bỉ, bền màu, chống bám bụi tối ưu.', dm:'Theo hướng dẫn' },
        { code:'JS-BenMauToiUu', name:'Jotashield Bền Màu Tối Ưu', spec:'1L / 5L', desc:'Bền màu dài lâu, ít bám bụi, chống rong rêu & nấm mốc, kháng tia UV tối đa.', dm:'Theo hướng dẫn' },
        { code:'JS-SachVuotTroi', name:'Jotashield Sạch Vượt Trội', spec:'1L / 5L / 15L', desc:'Chống bám bụi đột phá, tự làm sạch bề mặt, chống rong rêu & nấm mốc, giảm nhiệt, kháng UV.', dm:'Theo hướng dẫn' },
        { code:'JS-ChePhu-VetNut', name:'Jotashield Che Phủ Vết Nứt', spec:'5L', desc:'Đàn hồi cao cấp, che phủ vết nứt gấp 2 lần, ít bám bụi.', dm:'Theo hướng dẫn' },
        { code:'JS-ChongPhaiMau', name:'Jotashield Chống Phai Màu', spec:'5L / 15L', desc:'Chống nắng hiệu quả, giảm nhiệt, ngăn ngừa vệt nước, chống rong rêu & nấm mốc, chống bám bụi, chống thấm nước.', dm:'Theo hướng dẫn' },
      ],
      "Tough Shield": [
        { code:'TS-Max', name:'Tough Shield Max', spec:'5L / 17L', desc:'Kháng UV, chống rong rêu & nấm mốc, che phủ tốt.', dm:'Theo hướng dẫn' },
      ],
      "Chống thấm": [
        { code:'WaterGuard', name:'Jotun WaterGuard Chống thấm', spec:'20kg', desc:'Kháng thấm tối ưu, độ đàn hồi cao, dễ sử dụng, chống nấm mốc.', dm:'Theo hướng dẫn' },
      ],
    },
    "Sơn gỗ & Kim loại": {
      "Gardex": [
        { code:'Gardex-Primer', name:'Gardex Primer - Sơn lót gỗ', spec:'1L', desc:'Sơn lót Gardex nhẹ mùi, tăng cường độ bám dính.', dm:'Theo hướng dẫn' },
        { code:'Gardex-Bong', name:'Gardex Bóng - Sơn phủ gỗ', spec:'0.8L / 2.5L', desc:'Chống thấm, bền màu, nhẹ mùi, nhanh khô, chống nấm mốc và rỉ sét.', dm:'Theo hướng dẫn' },
      ],
    },
    "🧱 Sơn lót & Bột trét": {
      "Sơn lót": [
        { code:'Lot-Majestic', name:'Sơn lót chống kiềm Majestic', spec:'3L / 5L / 17L', desc:'Sơn lót chống kiềm cao cấp nội thất, tăng cường bám dính.', dm:'Theo hướng dẫn' },
        { code:'Lot-Essence', name:'Sơn lót chống kiềm Essence', spec:'3L / 5L', desc:'Sơn lót chống kiềm nội & ngoại thất, bám dính tốt, dễ thi công.', dm:'Theo hướng dẫn' },
        { code:'Alkyd-Xam', name:'Sơn lót chống rỉ Alkyd màu xám', spec:'5L / 20L', desc:'Sơn lót chống rỉ cho bề mặt kim loại.', dm:'Theo hướng dẫn' },
        { code:'Alkyd-Do', name:'Sơn lót chống rỉ Alkyd màu đỏ', spec:'5L / 20L', desc:'Sơn lót chống rỉ cho bề mặt kim loại.', dm:'Theo hướng dẫn' },
      ],
      "Bột trét": [
        { code:'Putty-IN-EX', name:'Jotun Interior & Exterior Putty', spec:'40kg', desc:'Bột trét cao cấp nội & ngoại thất.', dm:'Theo hướng dẫn' },
        { code:'Putty-EX', name:'Jotun Exterior Putty', spec:'40kg', desc:'Bột trét cao cấp ngoại thất.', dm:'Theo hướng dẫn' },
        { code:'Putty-IN', name:'Jotun Interior Putty', spec:'40kg', desc:'Bột trét cao cấp nội thất.', dm:'Theo hướng dẫn' },
      ],
    },
  },
  kova: {
    "🎨 Sơn nội thất": [
      { code:'K871 GOLD', name:'Sơn bóng nội thất cao cấp', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn bóng GOLD trong nhà, độ phủ cao, bền màu.', dm:'120-140 m²/20kg' },
      { code:'K5500 GOLD', name:'Sơn bóng nội thất', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn bóng trong nhà cao cấp.', dm:'90-100 m²/20kg' },
      { code:'K260 GOLD', name:'Sơn không bóng trong nhà', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn mịn không bóng nội thất chất lượng cao.', dm:'60-70 m²/20kg' },
      { code:'K771 GOLD', name:'Sơn trang trí nội thất', spec:'Thùng 25kg', desc:'Sơn trang trí nội thất độ bám dính cao.', dm:'75-88 m²/25kg' },
      { code:'K10 GOLD', name:'Sơn trần trang trí', spec:'Thùng 25kg', desc:'Sơn trần nhà, tường trang trí cao cấp.', dm:'125-150 m²/25kg' },
      { code:'K109 GOLD', name:'Sơn lót kháng kiềm nội thất', spec:'Thùng 25kg', desc:'Sơn lót kháng kiềm cao cấp trong nhà.', dm:'120-140 m²/25kg' },
    ],
    "🛡️ Sơn ngoại thất & Chống thấm": [
      { code:'K360 GOLD', name:'Sơn bóng ngoại thất cao cấp', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn bóng cao cấp ngoại thất, chịu thời tiết khắc nghiệt.', dm:'120-140 m²/20kg' },
      { code:'CT04T GOLD', name:'Sơn trang trí chống thấm ngoại thất', spec:'Thùng 20kg', desc:'Sơn trang trí, chống thấm cao cấp ngoài trời.', dm:'100-110 m²/20kg' },
      { code:'K5800 GOLD', name:'Sơn bóng ngoại thất', spec:'Thùng 20kg', desc:'Sơn bóng ngoại thất bền màu, chịu thời tiết.', dm:'Theo hướng dẫn' },
      { code:'CT-11A GOLD', name:'Chống thấm xi măng, bê tông', spec:'Thùng 20kg / Lon 4kg', desc:'Chống thấm sàn mái, tường, toilet, bể nước bằng xi măng polymer.', dm:'Tùy bề mặt' },
      { code:'CT-11B GOLD', name:'Phụ gia chống thấm xi măng', spec:'Thùng 19kg / Lon 3.8kg', desc:'Phụ gia trộn vữa xi măng, bê tông chống thấm.', dm:'Tùy bề mặt' },
      { code:'CT-14 GOLD', name:'Chống thấm co giãn chống áp lực ngược', spec:'Thùng 20kg / Lon 4kg', desc:'Chất chống thấm co giãn, chống áp lực ngược cho xi măng, bê tông.', dm:'Tùy bề mặt' },
    ],
    "🧱 Bột bả & Sàn": [
      { code:'MTN GOLD', name:'Matit ngoại thất', spec:'Bao 25kg', desc:'Bột bả ngoại thất chống thấm, chống nứt.', dm:'1,2-1,4 kg/m²' },
      { code:'KOVA-BT', name:'Bột bả cao cấp trong nhà', spec:'Bao 40kg', desc:'Bột bả trong nhà cao cấp, độ bám dính cao.', dm:'0,9-1,0 kg/m²' },
      { code:'KOVA-BN', name:'Bột bả cao cấp ngoại thất', spec:'Bao 40kg', desc:'Bột bả ngoại thất cao cấp, chống thấm.', dm:'0,9-1,0 kg/m²' },
      { code:'MB-T', name:'Bột bả trong nhà', spec:'Bao 25kg', desc:'Bột bả trong nhà, chất lượng kinh tế.', dm:'0,8-1,0 kg/m²' },
      { code:'MB-N', name:'Bột bả ngoại thất', spec:'Bao 25kg', desc:'Bột bả ngoại thất, giá hợp lý.', dm:'0,8-1,0 kg/m²' },
      { code:'CT08 GOLD', name:'Sơn sân tennis, sân thể thao', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn sân thể thao đa năng, chịu mài mòn, nhiều màu sắc.', dm:'Tùy bề mặt' },
      { code:'KL55T GOLD', name:'Sơn men bóng phủ sàn trong nhà', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn phủ sàn trong nhà, chịu mài mòn.', dm:'Theo hướng dẫn' },
      { code:'KLST GOLD', name:'Sơn men bóng phủ sàn chịu mài mòn', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn phủ sàn chịu mài mòn cao, hai thành phần.', dm:'2,0-2,5 kg/m²' },
      { code:'TNA GOLD', name:'Chất phủ đệm sàn thể thao', spec:'Bao 25kg', desc:'Chất phủ đệm cho sân tennis, sân thể thao đa năng.', dm:'Tùy bề mặt' },
    ],
  },
  nippon: {
    "🎨 Sơn nội thất": [
      { code:'Matex', name:'Sơn nội thất', spec:'Thùng 18L', desc:'Sơn nước nội thất chất lượng tốt, giá thành hợp lý, phủ cao.', dm:'14-16 m²/lớp' },
      { code:'SuperTech', name:'Sơn nội thất cao cấp', spec:'Thùng 18L', desc:'Không mùi, lau chùi dễ dàng, siêu bền.', dm:'12-14 m²/lớp' },
    ],
    "🛡️ Sơn ngoại thất": [
      { code:'Weatherbond', name:'Sơn ngoại thất chống thấm', spec:'Thùng 18L', desc:'Chống thấm, chống kiềm, bền màu ngoài trời.', dm:'12-14 m²/lớp' },
      { code:'Gold', name:'Sơn ngoại thất cao cấp', spec:'Thùng 18L', desc:'Bảo vệ tường vượt trội, 15 năm bền màu.', dm:'10-12 m²/lớp' },
    ],
  },
};

// Price map: brand_id -> { code: { price, spec } }
const PRICE_MAP = {
  munich: {
    // Chống thấm xi măng-polymer
    'G20':   { price:'1.925.950đ', spec:'Bộ 26kg (bột 16 + nước 10)' },
    'G20-20kg': { price:'1.629.650đ', spec:'Thùng 20kg' },
    'G20-5kg':  { price:'562.970đ', spec:'Lon 5kg' },
    'G20S':  { price:'1.431.000đ', spec:'Bộ 25kg' },
    'G20C':  { price:'1.143.718đ', spec:'Bộ 20kg' },
    'G20C-Đen': { price:'1.291.868đ', spec:'Bộ 20kg' },
    'C20':   { price:'1.232.608đ', spec:'Thùng 20kg' },
    // Acrylic & PU
    'CT0-5kg':   { price:'829.640đ', spec:'Lon 5kg' },
    'CT0-18kg':  { price:'3.022.260đ', spec:'Thùng 18kg' },
    'PU S700-1L':   { price:'247.104đ', spec:'Lon 1L' },
    'PU S700-4L':   { price:'1.035.180đ', spec:'Lon 4L' },
    'PU S700-18L':  { price:'3.858.624đ', spec:'Thùng 18L' },
    'PU S400-5L':   { price:'1.104.300đ', spec:'Lon 5L' },
    'PU S400-18L':  { price:'3.274.560đ', spec:'Thùng 18L' },
    'PU S800F-3.6kg': { price:'1.311.660đ', spec:'Bộ 3,6kg' },
    'PU S800F-18kg':  { price:'4.023.000đ', spec:'Bộ 18kg' },
    'Pu Glass-1L':  { price:'247.104đ', spec:'Lon 1L' },
    'Pu Glass-4L':  { price:'1.035.180đ', spec:'Lon 4L' },
    'Pu Glass-18L': { price:'3.858.624đ', spec:'Thùng 18L' },
    'Glass2K-3kg': { price:'1.600.020đ', spec:'Bộ 3kg' },
    'Glass2K-15kg':{ price:'6.666.750đ', spec:'Bộ 15kg' },
    'LiquidGlass-1kg': { price:'533.340đ', spec:'Bộ 1kg' },
    'LiquidGlass-3kg': { price:'1.511.130đ', spec:'Bộ 3kg' },
    'LiquidGlass-15kg':{ price:'7.333.425đ', spec:'Bộ 15kg' },
    'PrimeWater-1kg': { price:'162.965đ', spec:'Chai 1kg' },
    'PrimeWater-10kg':{ price:'1.185.200đ', spec:'Thùng 10kg' },
    'PrimerEP12-5kg': { price:'1.748.170đ', spec:'Bộ 5kg' },
    'PrimerEP12-25kg':{ price:'6.488.970đ', spec:'Bộ 25kg' },
    // Bitum
    'G10-18kg': { price:'1.629.650đ', spec:'Thùng 18kg' },
    'G10-3.5kg':{ price:'400.005đ', spec:'Lon 3,5kg' },
    'G68':    { price:'950.000đ', spec:'Thùng 18kg' },
    // AC02
    'AC02-5kg': { price:'1.007.420đ', spec:'Lon 5kg' },
    'AC02-18kg':{ price:'2.874.110đ', spec:'Thùng 18kg' },
    // S902
    'S902-5kg':  { price:'1.859.220đ', spec:'Bộ 5kg' },
    'S902-25kg': { price:'7.810.344đ', spec:'Bộ 25kg' },
    'S902Prime-3kg':  { price:'1.679.400đ', spec:'Bộ 3kg' },
    'S902Prime-15kg': { price:'6.866.424đ', spec:'Bộ 15kg' },
    // Walling & Stone
    'Walling-1L':  { price:'237.040đ', spec:'Chai 1L' },
    'Walling-5L':  { price:'918.530đ', spec:'Can 5L' },
    'Walling-25L': { price:'4.000.050đ', spec:'Can 25L' },
    'StoneSF-1L':  { price:'428.520đ', spec:'Lon 1L' },
    'StoneSF-4L':  { price:'1.928.340đ', spec:'Lon 4L' },
    'StoneSF-18L': { price:'7.713.360đ', spec:'Thùng 18L' },
    // Phụ gia
    'Latex-5L':  { price:'533.340đ', spec:'Can 5L' },
    'Latex-25L': { price:'2.518.550đ', spec:'Can 25L' },
    'Latex S-5kg':  { price:'400.000đ', spec:'Can 5kg' },
    'Latex S-25kg': { price:'1.700.000đ', spec:'Can 25kg' },
    'S808-1L':  { price:'207.410đ', spec:'Lon 1L' },
    'S808-5L':  { price:'948.160đ', spec:'Can 5L' },
    'S808-25L': { price:'4.340.795đ', spec:'Can 25L' },
    'S208':  { price:'234.077đ', spec:'Túi 1kg' },
    'S302':  { price:'174.817đ', spec:'Túi 1kg' },
    'Waterproof S206': { price:'595.000đ', spec:'Bao 20kg' },
    'Water Plug': { price:'162.965đ', spec:'Túi 1kg' },
    'Kyton K101':  { price:'1.000.540đ', spec:'Bao 20kg' },
    'CNI S699-5L':  { price:'592.000đ', spec:'Can 5L' },
    'CNI S699-25L': { price:'2.187.500đ', spec:'Can 25L' },
    'MN05-5L':  { price:'592.600đ', spec:'Can 5L' },
    'MN05-10L': { price:'1.083.000đ', spec:'Can 10L' },
    // Vữa & Keo
    'Grout G650-25kg': { price:'296.300đ', spec:'Bao 25kg' },
    'Grout G650-4kg':  { price:'103.705đ', spec:'Túi 4kg' },
    'Repair G50': { price:'503.710đ', spec:'Bao 25kg' },
    'HF-Xam':  { price:'251.855đ', spec:'Bao 25kg' },
    'HF-Mau':  { price:'444.450đ', spec:'Bao 25kg' },
    'Gel G01-C3': { price:'296.300đ', spec:'Bao 25kg' },
    'Gel G01-C2': { price:'362.968đ', spec:'Bao 25kg' },
    'Gel G01-C1': { price:'592.600đ', spec:'Bao 25kg' },
    'Tile G07':{ price:'47.408đ', spec:'Túi 1kg' },
    'Tile G07-Mau':{ price:'59.260đ', spec:'Túi 1kg' },
    'WS-1L': { price:'592.600đ', spec:'Chai 1L' },
    'WS-5L': { price:'2.222.250đ', spec:'Can 5L' },
  },
  sika: {
    'Sika Top 107': { price:'~810.000đ', spec:'Bao 25kg' },
    'Sikalastic 1K': { price:'~2.700.000đ', spec:'Thùng 20kg' },
    'Sika Latex':  { price:'~465.000đ', spec:'Can 5L' },
    'SikaGrout 214': { price:'~280.000đ', spec:'Bao 25kg' },
  },
  kova: {
    'K871 GOLD': { price:'5.020.000đ', spec:'20kg' },
    'K5500 GOLD': { price:'3.888.000đ', spec:'20kg' },
    'K260 GOLD': { price:'1.720.000đ', spec:'20kg' },
    'K360 GOLD': { price:'6.656.000đ', spec:'20kg' },
    'CT04T GOLD': { price:'4.755.000đ', spec:'20kg' },
    'CT-11A GOLD': { price:'4.445.000đ', spec:'20kg' },
    'CT-14 GOLD': { price:'4.210.000đ', spec:'20kg' },
    'MTN GOLD': { price:'855.000đ', spec:'25kg' },
    'CT08 GOLD': { price:'6.760.000đ', spec:'20kg' },
  },
  dulux: {
    'WS-RoyalShine-1L': { price:'680.000đ', spec:'1L' },
    'WS-RoyalShine-5L': { price:'2.980.000đ', spec:'5L' },
    'WS-Powerflexx-1L': { price:'640.000đ', spec:'1L' },
    'WS-Powerflexx-5L': { price:'2.890.000đ', spec:'5L' },
    'WS-CaoCap-1L': { price:'568.000đ', spec:'1L' },
    'WS-CaoCap-5L': { price:'2.544.000đ', spec:'5L' },
    'WS-CaoCap-15L': { price:'7.250.000đ', spec:'15L' },
    'WS-Colour': { price:'5.828.000đ', spec:'15L' },
    'IN-NgoaiThat-Bong': { price:'4.575.000đ', spec:'5L' },
    'IN-NgoaiThat-Mo-5L': { price:'1.500.000đ', spec:'5L' },
    'IN-NgoaiThat-Mo-15L': { price:'4.300.000đ', spec:'15L' },
    'IN-NgoaiThat-Mo-18L': { price:'5.145.000đ', spec:'18L' },
    'AM-Breathing': { price:'2.061.000đ', spec:'5L' },
    'AM-5in1-SieuBong': { price:'2.190.000đ', spec:'3L' },
    'AM-DiamondGlow-1L': { price:'415.000đ', spec:'1L' },
    'AM-DiamondGlow-5L': { price:'2.074.000đ', spec:'5L' },
    'EC-ChongBan-Bong-5L': { price:'1.236.000đ', spec:'5L' },
    'EC-ChongBan-Bong-15L': { price:'3.480.000đ', spec:'15L' },
    'EC-ChongBan-Mo-5L': { price:'1.180.000đ', spec:'5L' },
    'EC-ChongBan-Mo-15L': { price:'3.287.000đ', spec:'15L' },
    'EC-LauChuiVT-Bong-5L': { price:'1.046.000đ', spec:'5L' },
    'EC-LauChuiVT-Bong-15L': { price:'2.922.000đ', spec:'15L' },
    'EC-LauChuiVT-Mo-5L': { price:'998.000đ', spec:'5L' },
    'EC-LauChuiVT-Mo-15L': { price:'2.787.000đ', spec:'15L' },
    'IN-NoiThat-Bong-Moi': { price:'2.454.000đ', spec:'5L' },
    'IN-NoiThat-Mo-Moi': { price:'2.343.000đ', spec:'5L' },
    'EC-LauChuiHQ-Bong-5L': { price:'1.153.000đ', spec:'5L' },
    'EC-LauChuiHQ-Bong-18L': { price:'3.896.000đ', spec:'18L' },
    'EC-LauChuiHQ-Mo-5L': { price:'1.098.000đ', spec:'5L' },
    'EC-LauChuiHQ-Mo-18L': { price:'3.714.000đ', spec:'18L' },
    'Supersealer-5L': { price:'976.000đ', spec:'5L' },
    'Supersealer-18L': { price:'3.341.000đ', spec:'18L' },
    'AM-Primer-5L': { price:'889.000đ', spec:'5L' },
    'AM-Primer-18L': { price:'2.482.000đ', spec:'18L' },
    'IN-Primer-5L': { price:'869.000đ', spec:'5L' },
    'IN-Primer-18L': { price:'2.979.000đ', spec:'18L' },
    'EC-Primer-5L': { price:'783.000đ', spec:'5L' },
    'EC-Primer-15L': { price:'2.234.000đ', spec:'15L' },
    'Aquatech-Max-5kg': { price:'1.301.000đ', spec:'5kg' },
    'Aquatech-Max-20kg': { price:'4.126.000đ', spec:'20kg' },
    'Aquatech-Flex-6kg': { price:'1.275.000đ', spec:'6kg' },
    'Aquatech-Flex-20kg': { price:'4.014.000đ', spec:'20kg' },
    'Botret-IN-EX': { price:'866.000đ', spec:'40kg' },
    'Botret-IN': { price:'493.500đ', spec:'40kg' },
  },
  jotun: {
    'MJ-NguyenBan-1L':  { price:'545.000đ', spec:'1L' },
    'MJ-NguyenBan-5L':  { price:'2.325.000đ', spec:'5L' },
    'MJ-HoanHao-Bong5-5L':  { price:'1.730.000đ', spec:'5L' },
    'MJ-HoanHao-Mo-5L':  { price:'1.730.000đ', spec:'5L' },
    'ES-ChePhu-Bong-5L':  { price:'1.395.000đ', spec:'5L' },
    'ES-ChePhu-Mo-5L':  { price:'1.395.000đ', spec:'5L' },
    'ES-DeLauChui-5L':  { price:'1.179.000đ', spec:'5L' },
    'Jotaplast':  { price:'575.000đ', spec:'5L' },
    'JS-BenMauToanDien-5L':  { price:'3.315.000đ', spec:'5L' },
    'JS-BenMauToiUu-5L':  { price:'3.090.000đ', spec:'5L' },
    'JS-SachVuotTroi-5L':  { price:'2.515.000đ', spec:'5L' },
    'JS-ChePhu-VetNut-5L':  { price:'2.695.000đ', spec:'5L' },
    'JS-ChongPhaiMau-5L':  { price:'2.495.000đ', spec:'5L' },
    'TS-Max-5L':  { price:'1.730.000đ', spec:'5L' },
    'WaterGuard': { price:'4.172.000đ', spec:'20kg' },
    'Gardex-Primer': { price:'185.000đ', spec:'1L' },
    'Putty-IN-EX': { price:'510.000đ', spec:'40kg' },
    'Putty-EX':    { price:'490.000đ', spec:'40kg' },
    'Putty-IN':    { price:'370.000đ', spec:'40kg' },
  },
  nippon: {
    'Matex':  { price:'~1.130.000đ', spec:'Thùng 18L' },
    'Weatherbond': { price:'~1.290.000đ', spec:'Thùng 18L' },
  },
  nano: {
    'NO1-15L': { price:'4.983.000đ', spec:'15L' },
    'NO1-5L':  { price:'1.765.000đ', spec:'5L' },
    'NO1-1L':  { price:'418.000đ', spec:'1L' },
    'NO2-18L': { price:'4.818.000đ', spec:'18L' },
    'NO2-5L':  { price:'1.620.000đ', spec:'5L' },
    'NO3-18L': { price:'3.886.000đ', spec:'18L' },
    'NO3-5L':  { price:'1.128.000đ', spec:'5L' },
    'NO4-18L': { price:'2.818.000đ', spec:'18L' },
    'NO4-5L':  { price:'836.000đ', spec:'5L' },
    'NO5-18L': { price:'2.188.000đ', spec:'18L' },
    'NO5-5L':  { price:'720.000đ', spec:'5L' },
    'NO6-18L': { price:'2.458.000đ', spec:'18L' },
    'NO6-5L':  { price:'768.000đ', spec:'5L' },
    'NO7-18L': { price:'1.068.000đ', spec:'18L' },
    'NO7-5L':  { price:'389.000đ', spec:'5L' },
    'NA1-5L':  { price:'2.138.000đ', spec:'5L' },
    'NA1-1L':  { price:'496.000đ', spec:'1L' },
    'NA2-15L': { price:'5.818.000đ', spec:'15L' },
    'NA2-5L':  { price:'1.957.000đ', spec:'5L' },
    'NA2-1L':  { price:'474.000đ', spec:'1L' },
    'NA3-15L': { price:'4.398.000đ', spec:'15L' },
    'NA3-5L':  { price:'1.486.000đ', spec:'5L' },
    'NA4-18L': { price:'2.998.000đ', spec:'18L' },
    'NA4-5L':  { price:'958.000đ', spec:'5L' },
    'NA5-5L':  { price:'1.828.000đ', spec:'5L' },
    'NA5-1L':  { price:'458.000đ', spec:'1L' },
    'NA6-18L': { price:'4.428.000đ', spec:'18L' },
    'NA6-5L':  { price:'1.340.000đ', spec:'5L' },
    'NA7-18L': { price:'5.368.000đ', spec:'18L' },
    'NA7-5L':  { price:'1.566.000đ', spec:'5L' },
    'KT1-18L': { price:'1.605.000đ', spec:'18L' },
    'KT1-5L':  { price:'485.000đ', spec:'5L' },
    'KT2-18L': { price:'2.228.000đ', spec:'18L' },
    'KT2-5L':  { price:'708.000đ', spec:'5L' },
    'KT3-18L': { price:'2.737.000đ', spec:'18L' },
    'KT3-5L':  { price:'868.000đ', spec:'5L' },
    'KN1-18L': { price:'2.838.000đ', spec:'18L' },
    'KN1-5L':  { price:'898.000đ', spec:'5L' },
    'KN2-18L': { price:'3.788.000đ', spec:'18L' },
    'KN2-5L':  { price:'1.132.000đ', spec:'5L' },
    'KN3-18L': { price:'4.508.000đ', spec:'18L' },
    'KN3-5L':  { price:'1.365.000đ', spec:'5L' },
    'B1':      { price:'620.000đ', spec:'40kg' },
    'B2':      { price:'838.000đ', spec:'40kg' },
  },
};

function getPrice(bid, code) {
  const pm = PRICE_MAP[bid];
  if (!pm) return null;
  return pm[code] || null;
}

// Count products
for (const b of BRANDS) {
  const data = PRODUCTS[b.id];
  if (Array.isArray(data)) b.count = data.length;
  else { let c=0; for(const k in data) c+=data[k].length; b.count = c; }
}

const PRICES = [
  // --- MUNICH ---
  { brand:'Munich', product:'G20 - Màng chống thấm đàn hồi 200%', spec:'Bộ 25kg', price:'980.000đ' },
  { brand:'Munich', product:'G20 - Màng chống thấm đàn hồi 200%', spec:'Lon 5kg', price:'270.000đ' },
  { brand:'Munich', product:'G20C - Siêu cứng hiệu ứng lá sen', spec:'Bộ 20kg', price:'650.000đ' },
  { brand:'Munich', product:'PU S700 - Chống thấm PU đàn hồi 700%', spec:'Thùng 20kg', price:'2.083.000đ' },
  { brand:'Munich', product:'PU S700 - Chống thấm PU đàn hồi 700%', spec:'Lon 4kg', price:'525.000đ' },
  { brand:'Munich', product:'PU S400 - Chống thấm PU đàn hồi 400%', spec:'Thùng 18kg', price:'1.500.000đ' },
  { brand:'Munich', product:'AC02 - Chống thấm Acrylic', spec:'Thùng 18kg', price:'1.500.000đ' },
  { brand:'Munich', product:'CT0 - Chống thấm pha xi măng', spec:'Lon 5kg', price:'408.000đ' },
  { brand:'Munich', product:'G10 - Chống thấm gốc Bitum', spec:'Thùng 18kg', price:'780.000đ' },
  { brand:'Munich', product:'PU Glass - Chống thấm PU trong suốt', spec:'Thùng 20kg', price:'2.500.000đ' },
  { brand:'Munich', product:'Latex S - Phụ gia kết nối', spec:'Can 5L', price:'271.000đ' },
  { brand:'Munich', product:'Walling - Chống thấm tinh thể', spec:'Can 5L', price:'667.000đ' },
  { brand:'Munich', product:'Grout G650 - Vữa rót không co ngót', spec:'Bao 25kg', price:'146.000đ' },
  { brand:'Munich', product:'Repair G50 - Vữa sửa chữa bê tông', spec:'Bao 25kg', price:'271.000đ' },
  // --- KOVA ---
  { brand:'Kova', product:'K871 GOLD - Sơn bóng nội thất', spec:'20kg', price:'5.020.000đ' },
  { brand:'Kova', product:'K5500 GOLD - Sơn bóng nội thất', spec:'20kg', price:'3.888.000đ' },
  { brand:'Kova', product:'K260 GOLD - Sơn không bóng nội thất', spec:'20kg', price:'1.720.000đ' },
  { brand:'Kova', product:'K360 GOLD - Sơn bóng ngoại thất', spec:'20kg', price:'6.656.000đ' },
  { brand:'Kova', product:'CT04T GOLD - Trang trí chống thấm', spec:'20kg', price:'4.755.000đ' },
  { brand:'Kova', product:'CT-11A GOLD - Chống thấm', spec:'20kg', price:'4.445.000đ' },
  { brand:'Kova', product:'CT-14 GOLD - Chống thấm giãn', spec:'20kg', price:'4.210.000đ' },
  { brand:'Kova', product:'MTN GOLD - Matit ngoại thất', spec:'25kg', price:'855.000đ' },
  { brand:'Kova', product:'CT08 GOLD - Sơn sân tennis', spec:'20kg', price:'6.760.000đ' },
  // --- DULUX (giá tham khảo thị trường) ---
  { brand:'Dulux', product:'Weathershield Colour Protect - Ngoại thất', spec:'15L', price:'~3.280.000đ' },
  { brand:'Dulux', product:'Inspire - Sơn nội thất', spec:'18L', price:'~2.930.000đ' },
  { brand:'Dulux', product:'5in1 Ambiance - Nội thất cao cấp', spec:'5L', price:'~1.200.000đ' },
  { brand:'Dulux', product:'A1000 Professional - Nội thất', spec:'18L', price:'~2.110.000đ' },
  { brand:'Dulux', product:'Aquatech - Chống thấm', spec:'6kg', price:'~710.000đ' },
  { brand:'Dulux', product:'Bột trét tường', spec:'40kg', price:'~397.000đ' },
  // --- NIPPON (giá tham khảo thị trường) ---
  { brand:'Nippon', product:'Matex - Sơn nội thất', spec:'18L', price:'~1.130.000đ' },
  { brand:'Nippon', product:'Weatherbond - Sơn ngoại thất', spec:'18L', price:'~1.290.000đ' },
  { brand:'Nippon', product:'Weathergard Siêu bóng - Ngoại thất', spec:'5L', price:'~1.400.000đ' },
  { brand:'Nippon', product:'Odour-Less Spot-Less - Nội thất CC', spec:'18L', price:'~4.050.000đ' },
  { brand:'Nippon', product:'WP200 - Chống thấm', spec:'20kg', price:'~2.009.000đ' },
  // --- NANO HOUSE (Giá niêm yết chính hãng 02/02/2026 - Đã bao gồm VAT) ---
  { brand:'Nano House', product:'NO1 - SUPER INTERIOR (siêu bóng nội thất thượng hạng)', spec:'15L', price:'4.983.000đ' },
  { brand:'Nano House', product:'NO1 - SUPER INTERIOR (siêu bóng nội thất thượng hạng)', spec:'5L', price:'1.765.000đ' },
  { brand:'Nano House', product:'NO1 - SUPER INTERIOR (siêu bóng nội thất thượng hạng)', spec:'1L', price:'418.000đ' },
  { brand:'Nano House', product:'NO2 - ECO NANO GUARD (bóng nội thất cao cấp)', spec:'18L', price:'4.818.000đ' },
  { brand:'Nano House', product:'NO2 - ECO NANO GUARD (bóng nội thất cao cấp)', spec:'5L', price:'1.620.000đ' },
  { brand:'Nano House', product:'NO3 - ECO NANO GLOSSY (bóng nội thất cao cấp)', spec:'18L', price:'3.886.000đ' },
  { brand:'Nano House', product:'NO3 - ECO NANO GLOSSY (bóng nội thất cao cấp)', spec:'5L', price:'1.128.000đ' },
  { brand:'Nano House', product:'NO4 - ECO NANO CLEAN (bóng nội thất đặc biệt)', spec:'18L', price:'2.818.000đ' },
  { brand:'Nano House', product:'NO4 - ECO NANO CLEAN (bóng nội thất đặc biệt)', spec:'5L', price:'836.000đ' },
  { brand:'Nano House', product:'NO5 - ECO CLASSIC (mịn nội thất cao cấp)', spec:'18L', price:'2.188.000đ' },
  { brand:'Nano House', product:'NO5 - ECO CLASSIC (mịn nội thất cao cấp)', spec:'5L', price:'720.000đ' },
  { brand:'Nano House', product:'NO6 - ECO SUPER WHITE (siêu trắng trần)', spec:'18L', price:'2.458.000đ' },
  { brand:'Nano House', product:'NO6 - ECO SUPER WHITE (siêu trắng trần)', spec:'5L', price:'768.000đ' },
  { brand:'Nano House', product:'NO7 - ECO REGULAR (nội-ngoại thất đặc biệt)', spec:'18L', price:'1.068.000đ' },
  { brand:'Nano House', product:'NO7 - ECO REGULAR (nội-ngoại thất đặc biệt)', spec:'5L', price:'389.000đ' },
  { brand:'Nano House', product:'NA1 - SUPER EXTERIOR (siêu bóng ngoại thất thượng hạng)', spec:'5L', price:'2.138.000đ' },
  { brand:'Nano House', product:'NA1 - SUPER EXTERIOR (siêu bóng ngoại thất thượng hạng)', spec:'1L', price:'496.000đ' },
  { brand:'Nano House', product:'NA2 - ECO PRIMER EX (siêu bóng ngoại chống nóng)', spec:'15L', price:'5.818.000đ' },
  { brand:'Nano House', product:'NA2 - ECO PRIMER EX (siêu bóng ngoại chống nóng)', spec:'5L', price:'1.957.000đ' },
  { brand:'Nano House', product:'NA2 - ECO PRIMER EX (siêu bóng ngoại chống nóng)', spec:'1L', price:'474.000đ' },
  { brand:'Nano House', product:'NA3 - ECO NANO SHIELD (bóng ngoại thất cao cấp)', spec:'15L', price:'4.398.000đ' },
  { brand:'Nano House', product:'NA3 - ECO NANO SHIELD (bóng ngoại thất cao cấp)', spec:'5L', price:'1.486.000đ' },
  { brand:'Nano House', product:'NA4 - ECO PLATIUM (mịn ngoại thất cao cấp)', spec:'18L', price:'2.998.000đ' },
  { brand:'Nano House', product:'NA4 - ECO PLATIUM (mịn ngoại thất cao cấp)', spec:'5L', price:'958.000đ' },
  { brand:'Nano House', product:'NA5 - ECO CLEAR (siêu bóng ngoại chống nóng, trong suốt)', spec:'5L', price:'1.828.000đ' },
  { brand:'Nano House', product:'NA5 - ECO CLEAR (siêu bóng ngoại chống nóng, trong suốt)', spec:'1L', price:'458.000đ' },
  { brand:'Nano House', product:'NA6 - ECO PROGUARD (chống thấm cao cấp)', spec:'18L', price:'4.428.000đ' },
  { brand:'Nano House', product:'NA6 - ECO PROGUARD (chống thấm cao cấp)', spec:'5L', price:'1.340.000đ' },
  { brand:'Nano House', product:'NA7 - ECO PROGUARD MÀU (chống thấm màu cao cấp)', spec:'18L', price:'5.368.000đ' },
  { brand:'Nano House', product:'NA7 - ECO PROGUARD MÀU (chống thấm màu cao cấp)', spec:'5L', price:'1.566.000đ' },
  { brand:'Nano House', product:'KT1 - ECO SEALER (lót kiềm nội-ngoại thất)', spec:'18L', price:'1.605.000đ' },
  { brand:'Nano House', product:'KT1 - ECO SEALER (lót kiềm nội-ngoại thất)', spec:'5L', price:'485.000đ' },
  { brand:'Nano House', product:'KT2 - ECO SEALER (lót kiềm nội thất đặc biệt)', spec:'18L', price:'2.228.000đ' },
  { brand:'Nano House', product:'KT2 - ECO SEALER (lót kiềm nội thất đặc biệt)', spec:'5L', price:'708.000đ' },
  { brand:'Nano House', product:'KT3 - INTERIOR (lót kiềm nội thất cao cấp)', spec:'18L', price:'2.737.000đ' },
  { brand:'Nano House', product:'KT3 - INTERIOR (lót kiềm nội thất cao cấp)', spec:'5L', price:'868.000đ' },
  { brand:'Nano House', product:'KN1 - EX-MASTER (lót kiềm ngoại thất đặc biệt)', spec:'18L', price:'2.838.000đ' },
  { brand:'Nano House', product:'KN1 - EX-MASTER (lót kiềm ngoại thất đặc biệt)', spec:'5L', price:'898.000đ' },
  { brand:'Nano House', product:'KN2 - EX-TERIOR (lót kiềm ngoại thất cao cấp)', spec:'18L', price:'3.788.000đ' },
  { brand:'Nano House', product:'KN2 - EX-TERIOR (lót kiềm ngoại thất cao cấp)', spec:'5L', price:'1.132.000đ' },
  { brand:'Nano House', product:'KN3 - ECO PRIMER (lót kiềm ngoại thất thượng hạng)', spec:'18L', price:'4.508.000đ' },
  { brand:'Nano House', product:'KN3 - ECO PRIMER (lót kiềm ngoại thất thượng hạng)', spec:'5L', price:'1.365.000đ' },
  { brand:'Nano House', product:'B1 - HOME COAT (bột bả trong/ngoài)', spec:'40kg', price:'620.000đ' },
  { brand:'Nano House', product:'B2 - LEVEN COAT (bột bả chống thấm)', spec:'40kg', price:'838.000đ' },
  // --- SIKA (giá thị trường tham khảo) ---
  { brand:'Sika', product:'Sikalastic 1K - Chống thấm PU', spec:'Thùng 20kg', price:'~2.700.000đ' },
  { brand:'Sika', product:'SikaTop 107 Seal - Chống thấm bảo vệ', spec:'Bộ 25kg', price:'~810.000đ' },
  { brand:'Sika', product:'Sika Latex - Phụ gia chống thấm', spec:'Can 5L', price:'~465.000đ' },
  { brand:'Sika', product:'Sikagrout 214-11 - Vữa rót không co ngót', spec:'Bao 25kg', price:'~280.000đ' },
  { brand:'Sika', product:'Sikaflex 11FC - Keo trám khe', spec:'Ống 600ml', price:'Liên hệ' },
  // --- JOTUN (giá niêm yết tham khảo) ---
  { brand:'Jotun', product:'Jotashield Bền Màu Toàn Diện - Ngoại thất', spec:'15L', price:'~9.545.000đ' },
  { brand:'Jotun', product:'Jotashield Sạch Vượt Trội - Ngoại thất', spec:'15L', price:'~7.355.000đ' },
  { brand:'Jotun', product:'Jotashield Chống Phai Màu - Ngoại thất', spec:'15L', price:'~7.145.000đ' },
  { brand:'Jotun', product:'Jotun Water Guard - Chống thấm', spec:'20kg', price:'~4.170.000đ' },
  { brand:'Jotun', product:'Tough Shield Max - Ngoại thất kinh tế', spec:'17L', price:'~4.950.000đ' },
];
