/* LOGIC SẢN PHẨM - load data từ data.js */
function getPrice(bid, code) {
  const pm = PRICE_MAP[bid];
  if (!pm) return null;
  if (pm[code]) return pm[code];
  for (const key in pm) {
    if (code.startsWith(key)) return pm[key];
  }
  return null;
}

// Count products (hỗ trợ cả cây 2 cấp và 3 cấp)
for (const b of BRANDS) {
  const data = PRODUCTS[b.id];
  if (!data) { b.count = 0; continue; }
  if (Array.isArray(data)) { b.count = data.length; continue; }
  let c = 0;
  for (const k in data) {
    if (Array.isArray(data[k])) { c += data[k].length; }
    else {
      // Cây 3 cấp: Category → Subcategory → Array
      for (const sk in data[k]) {
        if (Array.isArray(data[k][sk])) c += data[k][sk].length;
      }
    }
  }
  b.count = c;
}

// Danh sách giá cho bảng giá (front-end display)
const PRICES = [
  // --- MUNICH - SƠN NƯỚC & CHỐNG THẤM (bảng giá 04/2026) ---
  { brand:'Munich', product:'Luxury Prime Lót kháng kiềm Nội thất', spec:'5L', price:'883.333đ' },
  { brand:'Munich', product:'Luxury Prime Lót kháng kiềm Nội thất', spec:'18L', price:'2.650.000đ' },
  { brand:'Munich', product:'Luxury Prime Lót kháng kiềm Ngoại thất', spec:'5L', price:'950.000đ' },
  { brand:'Munich', product:'Luxury Prime Lót kháng kiềm Ngoại thất', spec:'18L', price:'2.850.000đ' },
  { brand:'Munich', product:'Luxury Siêu bóng Nội thất', spec:'5L', price:'983.333đ' },
  { brand:'Munich', product:'Luxury Siêu bóng Nội thất', spec:'18L', price:'2.950.000đ' },
  { brand:'Munich', product:'Luxury Siêu bóng Ngoại thất', spec:'5L', price:'1.266.667đ' },
  { brand:'Munich', product:'Luxury Siêu bóng Ngoại thất', spec:'18L', price:'3.800.000đ' },
  { brand:'Munich', product:'Action Siêu mịn Nội thất', spec:'5L', price:'466.667đ' },
  { brand:'Munich', product:'Action Siêu mịn Nội thất', spec:'18L', price:'1.400.000đ' },
  { brand:'Munich', product:'Action Siêu mịn Ngoại thất', spec:'5L', price:'633.333đ' },
  { brand:'Munich', product:'Action Siêu mịn Ngoại thất', spec:'18L', price:'1.900.000đ' },
  { brand:'Munich', product:'Action Primer Lót kháng kiềm Nội thất', spec:'5L', price:'450.000đ' },
  { brand:'Munich', product:'Action Primer Lót kháng kiềm Nội thất', spec:'18L', price:'1.350.000đ' },
  { brand:'Munich', product:'Action Primer Lót kháng kiềm Ngoại thất', spec:'5L', price:'493.333đ' },
  { brand:'Munich', product:'Action Primer Lót kháng kiềm Ngoại thất', spec:'18L', price:'1.480.000đ' },
  { brand:'Munich', product:'Economy Kinh tế', spec:'5L', price:'190.000đ' },
  { brand:'Munich', product:'Economy Kinh tế', spec:'18L', price:'592.500đ' },
  { brand:'Munich', product:'FLY Bóng mờ Nội thất', spec:'5L', price:'780.000đ' },
  { brand:'Munich', product:'FLY Bóng mờ Nội thất', spec:'18L', price:'2.000.000đ' },
  { brand:'Munich', product:'FLY Bóng mờ Ngoại thất', spec:'5L', price:'870.000đ' },
  { brand:'Munich', product:'FLY Bóng mờ Ngoại thất', spec:'18L', price:'2.300.000đ' },
  { brand:'Munich', product:'Nano AB Diệt khuẩn Siêu bóng', spec:'5L', price:'2.943.333đ' },
  { brand:'Munich', product:'Nano AB Diệt khuẩn Siêu bóng', spec:'18L', price:'8.830.000đ' },
  { brand:'Munich', product:'UV20 Chống nóng', spec:'4L', price:'1.200.000đ' },
  { brand:'Munich', product:'UV20 Chống nóng', spec:'18L', price:'6.225.000đ' },
  { brand:'Munich', product:'UV20 Primer Lót chống nóng', spec:'4L', price:'1.200.000đ' },
  { brand:'Munich', product:'UV20 Primer Lót chống nóng', spec:'18L', price:'3.600.000đ' },
  { brand:'Munich', product:'Sport C631 Sân thể thao', spec:'5kg', price:'1.328.001đ' },
  { brand:'Munich', product:'Sport C631 Sân thể thao', spec:'18kg', price:'3.570.000đ' },
  { brand:'Munich', product:'Sport S632 Sân thể thao cao cấp', spec:'5kg', price:'2.451.999đ' },
  { brand:'Munich', product:'Sport S632 Sân thể thao cao cấp', spec:'18kg', price:'5.670.000đ' },
  { brand:'Munich', product:'Top S909 Bột bả Nội thất', spec:'25kg', price:'445.000đ' },
  { brand:'Munich', product:'Top S909 Bột bả Ngoại thất', spec:'25kg', price:'500.000đ' },
  // Munich chống thấm
  { brand:'Munich', product:'G20 Màng chống thấm đàn hồi 200%', spec:'Bộ 26kg', price:'1.925.950đ' },
  { brand:'Munich', product:'G20S Màng chống thấm đàn hồi 200%', spec:'Bộ 25kg', price:'1.431.000đ' },
  { brand:'Munich', product:'G20C Siêu cứng lá sen', spec:'Bộ 20kg', price:'1.143.718đ' },
  { brand:'Munich', product:'G20C-Đen Chống thấm bể cá Koi', spec:'Bộ 20kg', price:'1.291.868đ' },
  { brand:'Munich', product:'C20 Màng chống thấm siêu cứng', spec:'Thùng 20kg', price:'1.232.608đ' },
  { brand:'Munich', product:'CT0 Acrylic chống thấm pha xi măng', spec:'5kg', price:'829.640đ' },
  { brand:'Munich', product:'CT0 Acrylic chống thấm pha xi măng', spec:'18kg', price:'3.022.260đ' },
  { brand:'Munich', product:'PU S700 Chống thấm PU đàn hồi 700%', spec:'1L', price:'247.104đ' },
  { brand:'Munich', product:'PU S700 Chống thấm PU đàn hồi 700%', spec:'4L', price:'1.035.180đ' },
  { brand:'Munich', product:'PU S700 Chống thấm PU đàn hồi 700%', spec:'18L', price:'3.858.624đ' },
  { brand:'Munich', product:'PU S400 Chống thấm PU đàn hồi 400%', spec:'5L', price:'1.104.300đ' },
  { brand:'Munich', product:'PU S400 Chống thấm PU đàn hồi 400%', spec:'18L', price:'3.274.560đ' },
  { brand:'Munich', product:'PU S800F Chống thấm PU gốc dầu 700%', spec:'Bộ 3,6kg', price:'1.311.660đ' },
  { brand:'Munich', product:'PU S800F Chống thấm PU gốc dầu 700%', spec:'Bộ 18kg', price:'4.023.000đ' },
  { brand:'Munich', product:'Pu Glass Chống thấm PU trong suốt', spec:'1L', price:'247.104đ' },
  { brand:'Munich', product:'Pu Glass Chống thấm PU trong suốt', spec:'4L', price:'1.035.180đ' },
  { brand:'Munich', product:'Pu Glass Chống thấm PU trong suốt', spec:'18L', price:'3.858.624đ' },
  { brand:'Munich', product:'G10 Chống thấm Bitum-Polymer', spec:'3,5kg', price:'400.005đ' },
  { brand:'Munich', product:'G10 Chống thấm Bitum-Polymer', spec:'18kg', price:'1.629.650đ' },
  { brand:'Munich', product:'Grout G650 Vữa rót tự chảy', spec:'25kg', price:'296.300đ' },
  { brand:'Munich', product:'Repair G50 Vữa sửa chữa bê tông', spec:'25kg', price:'503.710đ' },
  { brand:'Munich', product:'Latex S Phụ gia kết nối chống thấm', spec:'5kg', price:'400.000đ' },
  { brand:'Munich', product:'Latex S Phụ gia kết nối chống thấm', spec:'25kg', price:'1.700.000đ' },
  { brand:'Munich', product:'S208 Phụ gia trộn vữa chống thấm', spec:'Túi 1kg', price:'234.077đ' },
  { brand:'Munich', product:'S302 Phụ gia chống co ngót', spec:'Túi 1kg', price:'174.817đ' },
  { brand:'Munich', product:'Walling Chống thấm tinh thể (nước)', spec:'1L', price:'237.040đ' },
  { brand:'Munich', product:'Walling Chống thấm tinh thể (nước)', spec:'5L', price:'918.530đ' },
  { brand:'Munich', product:'Water Plug Đông cứng nhanh', spec:'Túi 1kg', price:'162.965đ' },
  { brand:'Munich', product:'Kyton K101 Chống thấm tinh thể bột', spec:'20kg', price:'1.000.540đ' },
  { brand:'Munich', product:'Stone SF Chống thấm tinh thể (dầu)', spec:'1L', price:'428.520đ' },
  // Munich sơn công nghiệp
  { brand:'Munich', product:'Epoxy EP11 Lót', spec:'Bộ 15kg', price:'4.185.000đ' },
  { brand:'Munich', product:'Epoxy EP11 Lót', spec:'Bộ 3kg', price:'1.046.250đ' },
  { brand:'Munich', product:'Epoxy EP11 Phủ', spec:'Bộ 15kg', price:'4.050.000đ' },
  { brand:'Munich', product:'Epoxy EP11 Phủ', spec:'Bộ 3kg', price:'1.012.500đ' },
  { brand:'Munich', product:'Epoxy EP11 Tự san', spec:'Bộ 25kg', price:'6.785.270đ' },
  { brand:'Munich', product:'Epoxy EP12 Lót gốc nước', spec:'Bộ 25kg', price:'5.896.370đ' },
  { brand:'Munich', product:'Epoxy EP12 Phủ gốc nước', spec:'Bộ 25kg', price:'6.637.120đ' },
  { brand:'Munich', product:'S902 PU Kho lạnh chịu sốc nhiệt', spec:'Bộ 5kg', price:'1.859.220đ' },
  { brand:'Munich', product:'S106 Sơn chống gỉ Epoxy', spec:'Bộ 3kg', price:'983.716đ' },
  // --- JOTUN (bảng giá 04/2026) ---
  { brand:'Jotun', product:'Jotashield Bền Màu Toàn Diện', spec:'5L', price:'3.580.000đ' },
  { brand:'Jotun', product:'Jotashield Bền Màu Toàn Diện', spec:'15L', price:'9.715.000đ' },
  { brand:'Jotun', product:'Jotashield Bền Màu Tối Ưu', spec:'1L', price:'685.000đ' },
  { brand:'Jotun', product:'Jotashield Bền Màu Tối Ưu', spec:'5L', price:'3.335.000đ' },
  { brand:'Jotun', product:'Jotashield Sạch Vượt Trội', spec:'5L', price:'2.715.000đ' },
  { brand:'Jotun', product:'Jotashield Sạch Vượt Trội', spec:'15L', price:'7.945.000đ' },
  { brand:'Jotun', product:'Jotashield Che Phủ Vết Nứt', spec:'5L', price:'2.910.000đ' },
  { brand:'Jotun', product:'Jotashield Chống Phai Màu', spec:'5L', price:'2.695.000đ' },
  { brand:'Jotun', product:'Jotashield Chống Phai Màu', spec:'15L', price:'7.880.000đ' },
  { brand:'Jotun', product:'Tough Shield Max', spec:'5L', price:'1.815.000đ' },
  { brand:'Jotun', product:'Tough Shield Max', spec:'17L', price:'6.075.000đ' },
  { brand:'Jotun', product:'WaterGuard Chống thấm', spec:'6kg', price:'1.560.000đ' },
  { brand:'Jotun', product:'WaterGuard Chống thấm', spec:'20kg', price:'4.950.000đ' },
  { brand:'Jotun', product:'Majestic Đẹp Nguyên Bản', spec:'5L', price:'2.440.000đ' },
  { brand:'Jotun', product:'Majestic Đẹp Nguyên Bản', spec:'15L', price:'7.250.000đ' },
  { brand:'Jotun', product:'Majestic Sang Trọng (Bóng)', spec:'5L', price:'2.120.000đ' },
  { brand:'Jotun', product:'Majestic Sang Trọng (Bóng)', spec:'15L', price:'6.305.000đ' },
  { brand:'Jotun', product:'Majestic Đẹp Hoàn Hảo', spec:'5L', price:'1.815.000đ' },
  { brand:'Jotun', product:'Majestic Đẹp Hoàn Hảo', spec:'15L', price:'5.185.000đ' },
  { brand:'Jotun', product:'Essence Che Phủ Tối Đa', spec:'5L', price:'1.465.000đ' },
  { brand:'Jotun', product:'Essence Che Phủ Tối Đa', spec:'15L', price:'4.205.000đ' },
  { brand:'Jotun', product:'Essence Sơn Trắng Trần', spec:'5L', price:'1.215.000đ' },
  { brand:'Jotun', product:'Essence Sơn Trắng Trần', spec:'17L', price:'3.720.000đ' },
  { brand:'Jotun', product:'Essence Dễ Lau Chùi', spec:'5L', price:'1.240.000đ' },
  { brand:'Jotun', product:'Essence Dễ Lau Chùi', spec:'17L', price:'3.890.000đ' },
  { brand:'Jotun', product:'Jotaplast Kinh tế', spec:'5L', price:'605.000đ' },
  { brand:'Jotun', product:'Jotaplast Kinh tế', spec:'17L', price:'1.760.000đ' },
  { brand:'Jotun', product:'Majestic Primer Lót chống kiềm', spec:'5L', price:'1.215.000đ' },
  { brand:'Jotun', product:'Majestic Primer Lót chống kiềm', spec:'17L', price:'3.710.000đ' },
  { brand:'Jotun', product:'Essence Easy Primer', spec:'5L', price:'1.135.000đ' },
  { brand:'Jotun', product:'Essence Easy Primer', spec:'17L', price:'3.630.000đ' },
  { brand:'Jotun', product:'Alkyd Primer Chống rỉ xám', spec:'5L', price:'860.000đ' },
  { brand:'Jotun', product:'Alkyd Primer Chống rỉ xám', spec:'20L', price:'3.290.000đ' },
  { brand:'Jotun', product:'Alkyd Primer Chống rỉ đỏ', spec:'5L', price:'805.000đ' },
  { brand:'Jotun', product:'Alkyd Primer Chống rỉ đỏ', spec:'20L', price:'3.015.000đ' },
  { brand:'Jotun', product:'Interior & Exterior Putty', spec:'40kg', price:'535.000đ' },
  { brand:'Jotun', product:'Exterior Putty', spec:'40kg', price:'515.000đ' },
  { brand:'Jotun', product:'Interior Putty', spec:'40kg', price:'390.000đ' },
  { brand:'Jotun', product:'Gardex Primer', spec:'1L', price:'195.000đ' },
  { brand:'Jotun', product:'Gardex Bóng', spec:'2.5L', price:'570.000đ' },
  // --- NANO HOUSE ---
  { brand:'Nano House', product:'Super Interior NO1', spec:'5L', price:'1.765.000đ' },
  { brand:'Nano House', product:'Super Interior NO1', spec:'15L', price:'4.983.000đ' },
  { brand:'Nano House', product:'Eco Nano Guard NO2', spec:'5L', price:'1.620.000đ' },
  { brand:'Nano House', product:'Eco Nano Guard NO2', spec:'18L', price:'4.818.000đ' },
  { brand:'Nano House', product:'Super Exterior NA1', spec:'5L', price:'2.138.000đ' },
  { brand:'Nano House', product:'Eco Proguard Chống thấm NA6', spec:'5L', price:'1.340.000đ' },
  { brand:'Nano House', product:'Eco Proguard Chống thấm NA6', spec:'18L', price:'4.428.000đ' },
  // --- DULUX (bảng giá 07/2025 từ OCR) ---
  { brand:'Dulux', product:'Weathershield Royal Shine', spec:'1L', price:'660.000đ' },
  { brand:'Dulux', product:'Weathershield Royal Shine', spec:'5L', price:'2.980.000đ' },
  { brand:'Dulux', product:'Weathershield Powerflexx', spec:'1L', price:'640.000đ' },
  { brand:'Dulux', product:'Weathershield Powerflexx', spec:'5L', price:'2.580.000đ' },
  { brand:'Dulux', product:'Weathershield Cao cấp', spec:'1L', price:'570.000đ' },
  { brand:'Dulux', product:'Weathershield Cao cấp', spec:'5L', price:'2.580.000đ' },
  { brand:'Dulux', product:'Weathershield Cao cấp', spec:'18L', price:'7.350.000đ' },
  { brand:'Dulux', product:'Weathershield Colour Protect Bóng', spec:'5L', price:'2.045.000đ' },
  { brand:'Dulux', product:'Weathershield Colour Protect Mờ', spec:'5L', price:'1.500.000đ' },
  { brand:'Dulux', product:'Inspire Ngoại thất Bóng', spec:'5L', price:'1.575.000đ' },
  { brand:'Dulux', product:'Inspire Ngoại thất Bóng', spec:'15L', price:'5.145.000đ' },
  { brand:'Dulux', product:'Inspire Ngoại thất Mờ', spec:'5L', price:'1.575.000đ' },
  { brand:'Dulux', product:'Inspire Ngoại thất Mờ', spec:'15L', price:'4.518.000đ' },
  { brand:'Dulux', product:'Inspire Ngoại thất Mờ', spec:'18L', price:'5.400.000đ' },
  { brand:'Dulux', product:'Ambiance 5in1 Superflexx Siêu Bóng', spec:'5L', price:'2.234.000đ' },
  { brand:'Dulux', product:'Ambiance 5in1 Superflexx Bóng Mờ', spec:'5L', price:'2.122.000đ' },
  { brand:'Dulux', product:'Ambiance 5in1 Superflexx Bóng Mờ', spec:'18L', price:'6.075.000đ' },
  { brand:'Dulux', product:'Ambiance 5in1 Diamond Glow', spec:'5L', price:'2.137.000đ' },
  { brand:'Dulux', product:'EasyClean Chống Bám Bẩn KV Bóng', spec:'5L', price:'1.238.000đ' },
  { brand:'Dulux', product:'EasyClean Chống Bám Bẩn KV Mờ', spec:'5L', price:'1.180.000đ' },
  { brand:'Dulux', product:'EasyClean Lau Chùi Vượt Trội KV Bóng', spec:'5L', price:'1.046.000đ' },
  { brand:'Dulux', product:'EasyClean Lau Chùi Vượt Trội KV Mờ', spec:'5L', price:'998.000đ' },
  { brand:'Dulux', product:'Inspire Nội thất Bóng (Mới)', spec:'5L', price:'861.000đ' },
  { brand:'Dulux', product:'Inspire Nội thất Mờ (Mới)', spec:'5L', price:'820.000đ' },
  { brand:'Dulux', product:'EasyClean Lau Chùi Hiệu Quả Bóng', spec:'5L', price:'1.153.000đ' },
  { brand:'Dulux', product:'EasyClean Lau Chùi Hiệu Quả Mờ', spec:'5L', price:'1.098.000đ' },
  { brand:'Dulux', product:'Supersealer Lót nội thất', spec:'5L', price:'976.000đ' },
  { brand:'Dulux', product:'Supersealer Lót nội thất', spec:'18L', price:'3.341.000đ' },
  { brand:'Dulux', product:'Ambiance Primer Lót nội thất', spec:'5L', price:'869.000đ' },
  { brand:'Dulux', product:'Interior Primer Lót nội thất', spec:'5L', price:'869.000đ' },
  { brand:'Dulux', product:'EasyClean Primer Lót nội thất', spec:'5L', price:'783.000đ' },
  { brand:'Dulux', product:'Aquatech Max Chống thấm sàn', spec:'6kg', price:'1.301.000đ' },
  { brand:'Dulux', product:'Aquatech Max Chống thấm sàn', spec:'20kg', price:'4.126.000đ' },
  { brand:'Dulux', product:'Aquatech Flex Chống thấm tường', spec:'6kg', price:'1.275.000đ' },
  { brand:'Dulux', product:'Aquatech Flex Chống thấm tường', spec:'20kg', price:'4.014.000đ' },
  { brand:'Dulux', product:'Aquatech Vượt Trội', spec:'6kg', price:'1.274.000đ' },
  { brand:'Dulux', product:'Aquatech Vượt Trội', spec:'20kg', price:'4.010.000đ' },
  { brand:'Dulux', product:'Aquatech Bảo Vệ Cao cấp', spec:'6kg', price:'936.000đ' },
  { brand:'Dulux', product:'Bột trét Nội & Ngoại thất', spec:'40kg', price:'666.000đ' },
  { brand:'Dulux', product:'Bột trét Nội thất', spec:'40kg', price:'493.500đ' },
  // --- SIKA (bảng giá OCR) ---
  { brand:'Sika', product:'Sika Top 107 Vữa sửa chữa bê tông', spec:'25kg', price:'1.316.000đ' },
  { brand:'Sika', product:'Sika Latex Phụ gia chống thấm', spec:'5L', price:'185.000đ' },
  { brand:'Sika', product:'Sikaflex Pro-3 Keo trám khe', spec:'600ml', price:'382.000đ' },
  { brand:'Sika', product:'SikaGrout 214 Vữa rót không co ngót', spec:'25kg', price:'1.996.000đ' },
  // --- KOVA ---
  { brand:'Kova', product:'K871 GOLD Sơn bóng nội thất cao cấp', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'K871 GOLD Sơn bóng nội thất cao cấp', spec:'4kg', price:'Liên hệ' },
  { brand:'Kova', product:'K5500 GOLD Sơn bóng nội thất', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'K5500 GOLD Sơn bóng nội thất', spec:'4kg', price:'Liên hệ' },
  { brand:'Kova', product:'K260 GOLD Sơn không bóng trong nhà', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'K260 GOLD Sơn không bóng trong nhà', spec:'4kg', price:'Liên hệ' },
  { brand:'Kova', product:'K771 GOLD Sơn trang trí nội thất', spec:'25kg', price:'Liên hệ' },
  { brand:'Kova', product:'K10 GOLD Sơn trần trang trí', spec:'25kg', price:'Liên hệ' },
  { brand:'Kova', product:'K109 GOLD Sơn lót kháng kiềm nội thất', spec:'25kg', price:'Liên hệ' },
  { brand:'Kova', product:'K360 GOLD Sơn bóng ngoại thất cao cấp', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'K360 GOLD Sơn bóng ngoại thất cao cấp', spec:'4kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT04T GOLD Sơn trang trí chống thấm ngoại thất', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'K5800 GOLD Sơn bóng ngoại thất', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT-11A GOLD Chống thấm xi măng, bê tông', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT-11A GOLD Chống thấm xi măng, bê tông', spec:'4kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT-11B GOLD Phụ gia chống thấm xi măng', spec:'19kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT-11B GOLD Phụ gia chống thấm xi măng', spec:'3.8kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT-14 GOLD Chống thấm co giãn chống áp lực ngược', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT-14 GOLD Chống thấm co giãn chống áp lực ngược', spec:'4kg', price:'Liên hệ' },
  { brand:'Kova', product:'MTN GOLD Matit ngoại thất', spec:'25kg', price:'Liên hệ' },
  { brand:'Kova', product:'KOVA-BT Bột bả cao cấp trong nhà', spec:'40kg', price:'Liên hệ' },
  { brand:'Kova', product:'KOVA-BN Bột bả cao cấp ngoại thất', spec:'40kg', price:'Liên hệ' },
  { brand:'Kova', product:'MB-T Bột bả trong nhà', spec:'25kg', price:'Liên hệ' },
  { brand:'Kova', product:'MB-N Bột bả ngoại thất', spec:'25kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT08 GOLD Sơn sân tennis, sân thể thao', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT08 GOLD Sơn sân tennis, sân thể thao', spec:'4kg', price:'Liên hệ' },
  { brand:'Kova', product:'KL55T GOLD Sơn men bóng phủ sàn trong nhà', spec:'20kg', price:'Liên hệ' },
  { brand:'Kova', product:'CT05 Chống thấm', spec:'4kg', price:'Liên hệ' },
];
