/* DỮ LIỆU SẢN PHẨM - TRẦN HỮU MINH */
const BRANDS = [
  { id:'munich', name:'Munich', icon:'⭐', color:'#e94560', desc:'Chống thấm & Sơn công nghiệp - Phân phối chính thức', count:0 },
  { id:'nano', name:'Nano House', icon:'🏡', color:'#0fb9b1', desc:'Sơn & Chống thấm công nghệ Nano - Phân phối chính thức', count:0 },
  { id:'sika', name:'Sika', icon:'🧪', color:'#6c5ce7', desc:'Vữa kỹ thuật & Chống thấm', count:0 },
  { id:'dulux', name:'Dulux', icon:'🎨', color:'#0984e3', desc:'Sơn nội thất & ngoại thất', count:0 },
  { id:'jotun', name:'Jotun', icon:'🖌️', color:'#f39c12', desc:'Sơn nội thất & ngoại thất cao cấp', count:0 },
  { id:'kova', name:'Kova', icon:'🏺', color:'#e17055', desc:'Chống thấm & Sơn nước', count:0 },
  { id:'nippon', name:'Nippon', icon:'🇯🇵', color:'#00b894', desc:'Sơn nội thất & ngoại thất', count:0 },
];

const PRODUCTS = {
  munich: {
    "🎨 Sơn nước": {
      "Nội thất": [
        { code:'Luxury Prime NT', name:'Sơn lót kháng kiềm nội thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn lót kháng kiềm cao cấp cho tường nội thất.', dm:'Theo hướng dẫn' },
        { code:'Luxury - Siêu bóng NT', name:'Sơn siêu bóng nội thất', spec:'Lon 5L / Thùng 18L', desc:'Công nghệ Polymer cao cấp, siêu bóng, dễ lau chùi.', dm:'2-3 lớp, cách nhau 1-2 giờ' },
        { code:'Fly - Bóng mờ NT', name:'Sơn bóng mờ cao cấp nội thất', spec:'Lon 5L / Thùng 18L', desc:'Bóng mờ sang trọng, phù hợp mọi không gian.', dm:'2-3 lớp, cách 5-6 giờ' },
        { code:'Action - Siêu mịn NT', name:'Sơn siêu mịn nội thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn mịn chất lượng cao, giá hợp lý.', dm:'2 lớp, cách 30-60 phút' },
        { code:'Nano AB', name:'Sơn diệt khuẩn 99,99% nội thất', spec:'Lon 5L / Thùng 18L', desc:'Công nghệ Nano bạc diệt khuẩn. Dùng cho bệnh viện, trường học, nhà máy thực phẩm.', dm:'Theo hướng dẫn' },
        { code:'Economy', name:'Sơn kinh tế nội thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn nội thất giá rẻ, chất lượng cơ bản.', dm:'Theo hướng dẫn' },
      ],
      "Ngoại thất": [
        { code:'Luxury Prime NT2', name:'Sơn lót kháng kiềm ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn lót kháng kiềm cho tường ngoài trời.', dm:'Theo hướng dẫn' },
        { code:'Luxury - Siêu bóng NT2', name:'Sơn siêu bóng ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Siêu bóng ngoại thất, chịu thời tiết khắc nghiệt.', dm:'2-3 lớp' },
        { code:'Fly - Bóng mờ NT2', name:'Sơn bóng mờ cao cấp ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Bóng mờ ngoại thất, chịu thời tiết tốt.', dm:'Theo hướng dẫn' },
        { code:'Action - Siêu mịn NT2', name:'Sơn siêu mịn ngoại thất', spec:'Lon 5L / Thùng 18L', desc:'Sơn mịn ngoại thất chất lượng cao.', dm:'Theo hướng dẫn' },
      ],
    },
    "🛡️ Sơn chống thấm": {
      "Xi măng-polymer": [
        { code:'G20', name:'Màng chống thấm đàn hồi 200%', spec:'Bộ 26kg', desc:'Chống thấm hai thành phần xi măng-polymer siêu đàn hồi.', dm:'0,6 kg/m², 2-3 lớp' },
        { code:'G20S', name:'Màng chống thấm đàn hồi 200%', spec:'Bộ 25kg', desc:'Giống G20, quy cách khác.', dm:'0,6 kg/m², 2-3 lớp' },
        { code:'G20C', name:'Siêu cứng, hiệu ứng lá sen', spec:'Bộ 20kg', desc:'Chống thấm cao cấp hiệu ứng lá sen.', dm:'0,6-1 kg/m²/lớp' },
        { code:'G20C-Đen', name:'Chống thấm màu đen bể cá Koi', spec:'Bộ 20kg', desc:'Chuyên cho bể cá Koi, an toàn cho sinh vật.', dm:'0,6-1 kg/m²/lớp' },
        { code:'C20', name:'Màng chống thấm siêu cứng', spec:'Thùng 20kg', desc:'Lót cho PU S700, S400, chống thấm tường ngoài.', dm:'0,6-1 kg/m²/lớp' },
      ],
      "Acrylic": [
        { code:'CT0', name:'Acrylic chống thấm pha xi măng', spec:'Lon 5kg / Thùng 18kg', desc:'Chống thấm sàn mái, ban công, tường ngoài.', dm:'1kg + 0,5kg xi măng + 0,3kg nước' },
      ],
      "Polyurethane (PU)": [
        { code:'PU S700', name:'Chống thấm PU 1 TP (gốc nước) - đàn hồi 700%', spec:'Lon 1L/4L / Thùng 18L', desc:'Chống thấm lộ thiên, chịu UV. Hơn 1.000 màu.', dm:'0,75 kg/m²/lớp' },
        { code:'PU S400', name:'Chống thấm PU 1 TP (gốc nước) - đàn hồi 400%', spec:'Lon 5L / Thùng 18L', desc:'Giống S700, giá hợp lý hơn.', dm:'~6 m²/lớp' },
        { code:'PU S800F', name:'Chống thấm PU 2 TP (gốc dầu) - đàn hồi 700%', spec:'Bộ 3,6kg/18kg', desc:'Chống thấm lộ thiên, cần lót EP11.', dm:'1 kg/m²' },
        { code:'Pu Glass', name:'Chống thấm PU trong suốt - đàn hồi 600%', spec:'Lon 1L/4L / Thùng 18L', desc:'Màng chống thấm trong suốt 1 TP gốc nước.', dm:'0,75 kg/m²/lớp' },
      ],
      "Bitum & Đặc chủng": [
        { code:'G10', name:'Chống thấm Bitum-Polymer', spec:'Thùng 18kg / Lon 3,5kg', desc:'Chống thấm mái bằng, tầng hầm, WC.', dm:'Lót 0,2-0,3; Phủ 0,6 kg/m²/lớp' },
        { code:'G68', name:'Bitum nhựa đường biến tính', spec:'Thùng 18kg', desc:'Lớp lót cho màng khò Bitum.', dm:'Theo hướng dẫn' },
        { code:'S902', name:'Sơn sàn PU kho lạnh', spec:'Bộ 5kg/25kg', desc:'Chịu sốc nhiệt, chịu UV.', dm:'1 kg/m²/2 lớp' },
      ],
    },
    "🏭 Sơn công nghiệp": {
      "Epoxy": [
        { code:'EP11 Lót', name:'Sơn lót Epoxy gốc dung môi', spec:'Bộ 15kg/3kg', desc:'Lót cho sơn Epoxy và PU.', dm:'~100 m²/lớp' },
        { code:'EP11 Phủ', name:'Sơn phủ Epoxy hệ lăn', spec:'Bộ 15kg/3kg', desc:'Sơn phủ Epoxy cho sàn nhà xưởng.', dm:'~100 m²/lớp' },
        { code:'EP11 Tự san', name:'Sơn Epoxy tự san phẳng', spec:'Bộ 25kg/5kg', desc:'Tự san phẳng, dày ≥2mm.', dm:'1 kg/m²/dày 1mm' },
        { code:'EP12 Lót', name:'Sơn lót Epoxy gốc nước', spec:'Bộ 25kg/5kg', desc:'Không độc, không mùi.', dm:'~150 m²/lớp' },
        { code:'EP12 Phủ', name:'Sơn phủ Epoxy gốc nước', spec:'Bộ 25kg/5kg', desc:'Thân thiện môi trường.', dm:'~150 m²/lớp' },
      ],
      "Chống nóng & Thể thao": [
        { code:'UV20', name:'Sơn chống nóng cách nhiệt', spec:'Thùng 4L/18L', desc:'Giảm 5-28°C bề mặt mái.', dm:'Theo hướng dẫn' },
        { code:'UV20 Primer', name:'Lót chống nóng cho tôn cũ', spec:'Thùng 4L/18L', desc:'Lớp lót cho mái tôn cũ.', dm:'Theo hướng dẫn' },
        { code:'S632', name:'Sơn sân chơi thể thao', spec:'Lon 5L / Thùng 18L', desc:'Sơn trắng cho sân thể thao.', dm:'Theo hướng dẫn' },
      ],
    },
    "🔧 Phụ gia & VLXD": {
      "Phụ gia chống thấm": [
        { code:'Latex S', name:'Phụ gia kết nối chống thấm', spec:'Can 5kg/25kg', desc:'Làm hồ dầu, vữa trát chống thấm.', dm:'Theo hướng dẫn' },
        { code:'S208', name:'Phụ gia trộn vữa chống thấm', spec:'Túi 1kg', desc:'4-7 bao xi măng.', dm:'Theo hướng dẫn' },
        { code:'S302', name:'Phụ gia trộn vữa chống co ngót', spec:'Túi 1kg', desc:'Chống co ngót, tăng bám dính.', dm:'Theo hướng dẫn' },
        { code:'Walling', name:'Chống thấm tinh thể thẩm thấu (nước)', spec:'Chai 1L / Can 5L/25L', desc:'Chống muối hóa cho gạch, ngói, bê tông.', dm:'2-3 m²/lớp' },
        { code:'Stone SF', name:'Chống thấm tinh thể thẩm thấu (dầu)', spec:'Lon 1L/4L / Thùng 18L', desc:'Không lăn sơn nước lên trên được.', dm:'1-10 m²/lớp' },
        { code:'Kyton K101', name:'Chống thấm tinh thể dạng bột', spec:'Bao 20kg', desc:'Chống thấm thuận và nghịch.', dm:'2-5 kg/m²' },
        { code:'Water Plug', name:'Vật liệu đông cứng nhanh', spec:'Túi 1kg', desc:'Bịt kín lỗ rò rỉ nước tức thời.', dm:'Tức thời' },
      ],
      "Vữa & Keo dán": [
        { code:'Grout G650', name:'Vữa rót tự chảy không co ngót', spec:'Bao 25kg / Túi 4kg', desc:'Đổ cổ ống, hộp kỹ thuật.', dm:'1 m³ = 76 bao' },
        { code:'Repair G50', name:'Vữa sửa chữa bê tông', spec:'Bao 25kg', desc:'Sửa chữa bê tông hư hỏng.', dm:'10 m²/3 lớp' },
        { code:'Gel G-01', name:'Keo dán gạch đá', spec:'Bao 25kg', desc:'C1/C2/C3 tùy kích thước gạch.', dm:'Theo hướng dẫn' },
        { code:'Tile G07', name:'Keo chà ron miết mạch', spec:'Túi 1kg', desc:'Nhiều màu sắc.', dm:'1kg + 0,3L nước' },
        { code:'HF', name:'Bột rắc tăng cứng sàn', spec:'Bao 25kg', desc:'Tăng cứng sàn, chống mài mòn.', dm:'Theo hướng dẫn' },
      ],
    },
  },
  nano: {
    "Sơn phủ nội thất": [
      { code:'NO1', name:'SUPER INTERIOR - Sơn siêu bóng nội thất thượng hạng', spec:'15L / 5L / 1L', desc:'Bóng ngọc trai, bền màu gấp 3 lần, lau chùi hiệu quả, kháng khuẩn, chống nấm mốc. Sơn sinh thái eco, không APO, phooc môn, kim loại nặng.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO2', name:'ECO NANO GUARD - Sơn bóng nội thất cao cấp', spec:'18L / 5L', desc:'Công nghệ nano, màng sơn bóng công nghệ mới, lau chùi hiệu quả, kháng khuẩn, chống nấm mốc, an toàn sức khỏe.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO3', name:'ECO NANO GLOSSY - Sơn bóng nội thất cao cấp', spec:'18L / 5L', desc:'Công nghệ nano, lau chùi hiệu quả, kháng khuẩn, chống nấm mốc, màu sắc sắc nét, thân thiện môi trường.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO4', name:'ECO NANO CLEAN - Sơn bóng nội thất đặc biệt', spec:'18L / 5L', desc:'Công nghệ nano, lau chùi hiệu quả, chống nấm mốc, màu sắc sắc nét, thân thiện môi trường.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO5', name:'ECO CLASSIC - Sơn mịn nội thất cao cấp', spec:'18L / 5L', desc:'Màng sơn mịn, dễ lau chùi, không chì, thủy ngân, kim loại nặng, chống nấm mốc.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO6', name:'ECO SUPER WHITE - Sơn siêu trắng trần', spec:'18L / 5L', desc:'Siêu trắng sáng, chống nấm mốc hiệu quả, độ phủ cao.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NO7', name:'ECO REGULAR - Sơn nội – ngoại thất đặc biệt', spec:'18L / 5L', desc:'Màng sơn mờ, độ phủ cao, dễ thi công, màu sắc đẹp và đa dạng.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
    "Sơn phủ ngoại thất": [
      { code:'NA1', name:'SUPER EXTERIOR - Sơn siêu bóng ngoại thất thượng hạng', spec:'5L / 1L', desc:'Chống bám bụi, bền màu gấp 5 lần, giảm nhiệt chống nóng, chống thấm, chống nấm mốc, kháng tia UV, cọ rửa tối đa. Sơn sinh thái eco.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA2', name:'ECO PRIMER EX - Sơn siêu bóng ngoại chống nóng cao cấp', spec:'15L / 5L / 1L', desc:'Chống bám bụi bền màu gấp 3 lần, giảm nhiệt chống nóng hiệu quả, chống thấm, chống nấm mốc, kháng tia UV. Sơn sinh thái eco.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA3', name:'ECO NANO SHIELD - Sơn bóng ngoại thất cao cấp', spec:'15L / 5L', desc:'Lau chùi hiệu quả, màng sơn tự làm sạch, chống thấm, chống rong rêu nấm mốc, an toàn sức khỏe.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA4', name:'ECO PLATIUM - Sơn mịn ngoại thất cao cấp', spec:'18L / 5L', desc:'Màu sắc rực rỡ, dễ lau chùi, bền màu, kháng khuẩn, màng sơn láng mịn, chịu thời tiết khắc nghiệt.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA5', name:'ECO CLEAR - Sơn siêu bóng ngoại chống nóng cao cấp', spec:'5L / 1L', desc:'Phủ bóng trong suốt, lau chùi hiệu quả tối đa, màng bóng đẹp trang trí và bảo vệ màng sơn trong.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA6', name:'ECO PROGUARD - Sơn chống thấm cao cấp', spec:'18L / 5L', desc:'Chống thấm cho sàn, mái, tường đứng, khu WC. Tăng tuổi thọ công trình.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'NA7', name:'ECO PROGUARD MÀU - Sơn chống thấm màu cao cấp', spec:'18L / 5L', desc:'Chống thấm đa màu Acrylic kết hợp silicone gốc nước, chống thấm tối ưu, màu bền đẹp.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
    "Sơn lót chống kiềm": [
      { code:'KT1', name:'ECO SEALER - Sơn lót kiềm nội – ngoại thất', spec:'18L / 5L', desc:'Chống kiềm hóa, chống rêu mốc, bảo vệ lớp sơn phủ.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KT2', name:'ECO SEALER - Sơn lót kiềm nội thất đặc biệt', spec:'18L / 5L', desc:'Chống kiềm hóa, chống rêu mốc, độ phủ cao, chống phai màu, bảo vệ lớp sơn phủ.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KT3', name:'INTERIOR - Sơn lót kiềm nội thất cao cấp', spec:'18L / 5L', desc:'Chống kiềm hoàn hảo, độ phủ cao, chống rêu mốc, tăng bám dính, bảo vệ lớp sơn màu.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KN1', name:'EX-MASTER - Sơn lót kiềm ngoại thất đặc biệt', spec:'18L / 5L', desc:'Chống kiềm và muối hóa hoàn hảo, chống rêu mốc, tăng gấp 2 bám dính cho sơn màu.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KN2', name:'EX-TERIOR - Sơn lót kiềm ngoại thất cao cấp', spec:'18L / 5L', desc:'Chống kiềm và muối hóa hoàn hảo, độ phủ cao, chống rêu mốc, tăng gấp 2 bám dính.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'KN3', name:'ECO PRIMER - Sơn lót kiềm ngoại thất thượng hạng', spec:'18L / 5L', desc:'Siêu chống kiềm, chống muối hóa hoàn hảo, độ phủ cao, chống rêu mốc, bảo vệ màu, tăng gấp 2 bám dính.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
    "Bột bả": [
      { code:'B1', name:'HOME COAT - Bột bả trong và ngoài cao cấp', spec:'40kg', desc:'Bột bả trong và ngoài cao cấp.', dm:'Theo hướng dẫn nhà sản xuất' },
      { code:'B2', name:'LEVEN COAT - Bột bả chống thấm cao cấp', spec:'40kg', desc:'Bột bả chống thấm cao cấp.', dm:'Theo hướng dẫn nhà sản xuất' },
    ],
  },
  sika: {
    "🧪 Chống thấm & Vữa": [
      { code:'Sika Top 107', name:'Vữa sửa chữa bê tông', spec:'Bao 25kg', desc:'Vữa gốc xi măng polymer. Sửa chữa bê tông hư hỏng, trám vá.', dm:'~2 kg/m²' },
      { code:'Sikalastic 1K', name:'Màng chống thấm lỏng PU một thành phần', spec:'Thùng 20kg', desc:'Màng chống thấm gốc PU, đàn hồi cao, chịu UV.', dm:'1 kg/m²/lớp' },
      { code:'Sika Latex', name:'Phụ gia chống thấm', spec:'Can 5L/25L', desc:'Phụ gia trộn vữa chống thấm, tăng kết dính, chống thấm.', dm:'0,5L/bao xi măng' },
      { code:'SikaGrout 214', name:'Vữa rót tự chảy không co ngót', spec:'Bao 25kg', desc:'Rót móng máy, neo bulon. Cường độ cao, không co ngót.', dm:'~1 m²/25kg' },
    ],
    "🔧 Keo & Phụ kiện": [
      { code:'Sikaflex 11FC', name:'Keo trám khe đa năng', spec:'Ống 600ml', desc:'Keo PU trám khe co giãn, chịu thời tiết khắc nghiệt.', dm:'Theo khe hở' },
    ],
  },
  dulux: {
    "🎨 Sơn nội thất": [
      { code:'Inspire', name:'Sơn nội thất cao cấp', spec:'Thùng 18L', desc:'Sơn nội thất sang trọng, lau sạch vết bẩn dễ dàng.', dm:'14-16 m²/lớp' },
      { code:'5in1', name:'Sơn nội thất đa năng', spec:'Thùng 18L', desc:'5 tác dụng: chống kiềm, chống bám bụi, dễ lau chùi, bền màu, phủ tốt.', dm:'14-16 m²/lớp' },
      { code:'Ambiance', name:'Sơn nội thất cao cấp nhất', spec:'Thùng 18L', desc:'Không mùi, chống khuẩn, siêu bền. Dòng sơn cao cấp nhất của Dulux.', dm:'12-14 m²/lớp' },
    ],
    "🛡️ Sơn ngoại thất": [
      { code:'WeatherShield', name:'Sơn ngoại thất chống thấm cao cấp', spec:'Thùng 18L', desc:'Chống thấm, chống kiềm, bền màu ngoài trời. Công nghệ bảo vệ vượt trội.', dm:'12-14 m²/lớp' },
    ],
  },
  jotun: {
    "🎨 Sơn nội thất": [
      { code:'Majestic', name:'Sơn nội thất cao cấp', spec:'Thùng 18L', desc:'Sơn nội thất sang trọng với bảng màu rộng. Độ phủ cao.', dm:'12-14 m²/lớp' },
      { code:'Fenomastic', name:'Sơn nội thất giá cạnh tranh', spec:'Thùng 18L', desc:'Sơn nội thất chất lượng, giá thành hợp lý.', dm:'14-16 m²/lớp' },
    ],
    "🛡️ Sơn ngoại thất": [
      { code:'Jotashield', name:'Sơn ngoại thất chống thấm', spec:'Thùng 18L', desc:'Chống thấm, chống kiềm, chống bám bụi cho tường ngoài.', dm:'10-12 m²/lớp' },
      { code:'Gardex', name:'Sơn ngoại thất chất lượng', spec:'Thùng 18L', desc:'Sơn ngoại thất chống thấm giá phải chăng, chất lượng tốt.', dm:'12-14 m²/lớp' },
    ],
  },
  kova: {
    "🎨 Sơn nội thất": [
      { code:'K871 GOLD', name:'Sơn bóng nội thất cao cấp', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn bóng GOLD trong nhà, độ phủ cao, bền màu.', dm:'120-140 m²/20kg' },
      { code:'K5500 GOLD', name:'Sơn bóng nội thất', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn bóng trong nhà cao cấp.', dm:'90-100 m²/20kg' },
      { code:'K260 GOLD', name:'Sơn không bóng trong nhà', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn mịn không bóng nội thất chất lượng cao.', dm:'60-70 m²/20kg' },
      { code:'K771 GOLD', name:'Sơn trang trí nội thất', spec:'Thùng 25kg', desc:'Sơn trang trí nội thất độ bám dính cao.', dm:'75-88 m²/25kg' },
      { code:'K10 GOLD', name:'Sơn trần trang trí', spec:'Thùng 25kg', desc:'Sơn trần nhà, tường trang trí cao cấp.', dm:'125-150 m²/25kg' },
      { code:'K109 GOLD', name:'Sơn lót kháng kiềm nội thất', spec:'Thùng 25kg', desc:'Sơn lót kháng kiềm cao cấp trong nhà.', dm:'120-140 m²/25kg' },
    ],
    "🛡️ Sơn ngoại thất & Chống thấm": [
      { code:'K360 GOLD', name:'Sơn bóng ngoại thất cao cấp', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn bóng cao cấp ngoại thất, chịu thời tiết khắc nghiệt.', dm:'120-140 m²/20kg' },
      { code:'CT04T GOLD', name:'Sơn trang trí chống thấm ngoại thất', spec:'Thùng 20kg', desc:'Sơn trang trí, chống thấm cao cấp ngoài trời.', dm:'100-110 m²/20kg' },
      { code:'K5800 GOLD', name:'Sơn bóng ngoại thất', spec:'Thùng 20kg', desc:'Sơn bóng ngoại thất bền màu, chịu thời tiết.', dm:'Theo hướng dẫn' },
      { code:'CT-11A GOLD', name:'Chống thấm xi măng, bê tông', spec:'Thùng 20kg / Lon 4kg', desc:'Chống thấm sàn mái, tường, toilet, bể nước bằng xi măng polymer.', dm:'Tùy bề mặt' },
      { code:'CT-11B GOLD', name:'Phụ gia chống thấm xi măng', spec:'Thùng 19kg / Lon 3.8kg', desc:'Phụ gia trộn vữa xi măng, bê tông chống thấm.', dm:'Tùy bề mặt' },
      { code:'CT-14 GOLD', name:'Chống thấm co giãn chống áp lực ngược', spec:'Thùng 20kg / Lon 4kg', desc:'Chất chống thấm co giãn, chống áp lực ngược cho xi măng, bê tông.', dm:'Tùy bề mặt' },
    ],
    "🧱 Bột bả & Sàn": [
      { code:'MTN GOLD', name:'Matit ngoại thất', spec:'Bao 25kg', desc:'Bột bả ngoại thất chống thấm, chống nứt.', dm:'1,2-1,4 kg/m²' },
      { code:'KOVA-BT', name:'Bột bả cao cấp trong nhà', spec:'Bao 40kg', desc:'Bột bả trong nhà cao cấp, độ bám dính cao.', dm:'0,9-1,0 kg/m²' },
      { code:'KOVA-BN', name:'Bột bả cao cấp ngoại thất', spec:'Bao 40kg', desc:'Bột bả ngoại thất cao cấp, chống thấm.', dm:'0,9-1,0 kg/m²' },
      { code:'MB-T', name:'Bột bả trong nhà', spec:'Bao 25kg', desc:'Bột bả trong nhà, chất lượng kinh tế.', dm:'0,8-1,0 kg/m²' },
      { code:'MB-N', name:'Bột bả ngoại thất', spec:'Bao 25kg', desc:'Bột bả ngoại thất, giá hợp lý.', dm:'0,8-1,0 kg/m²' },
      { code:'CT08 GOLD', name:'Sơn sân tennis, sân thể thao', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn sân thể thao đa năng, chịu mài mòn, nhiều màu sắc.', dm:'Tùy bề mặt' },
      { code:'KL55T GOLD', name:'Sơn men bóng phủ sàn trong nhà', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn phủ sàn trong nhà, chịu mài mòn.', dm:'Theo hướng dẫn' },
      { code:'KLST GOLD', name:'Sơn men bóng phủ sàn chịu mài mòn', spec:'Thùng 20kg / Lon 4kg', desc:'Sơn phủ sàn chịu mài mòn cao, hai thành phần.', dm:'2,0-2,5 kg/m²' },
      { code:'TNA GOLD', name:'Chất phủ đệm sàn thể thao', spec:'Bao 25kg', desc:'Chất phủ đệm cho sân tennis, sân thể thao đa năng.', dm:'Tùy bề mặt' },
    ],
  },
  nippon: {
    "🎨 Sơn nội thất": [
      { code:'Matex', name:'Sơn nội thất', spec:'Thùng 18L', desc:'Sơn nước nội thất chất lượng tốt, giá thành hợp lý, phủ cao.', dm:'14-16 m²/lớp' },
      { code:'SuperTech', name:'Sơn nội thất cao cấp', spec:'Thùng 18L', desc:'Không mùi, lau chùi dễ dàng, siêu bền.', dm:'12-14 m²/lớp' },
    ],
    "🛡️ Sơn ngoại thất": [
      { code:'Weatherbond', name:'Sơn ngoại thất chống thấm', spec:'Thùng 18L', desc:'Chống thấm, chống kiềm, bền màu ngoài trời.', dm:'12-14 m²/lớp' },
      { code:'Gold', name:'Sơn ngoại thất cao cấp', spec:'Thùng 18L', desc:'Bảo vệ tường vượt trội, 15 năm bền màu.', dm:'10-12 m²/lớp' },
    ],
  },
};

// Price map: brand_id -> { code: { price, spec } }
const PRICE_MAP = {
  munich: {
    'G20':   { price:'980.000đ - 1.200.000đ', spec:'Bộ 25-26kg' },
    'G20S':  { price:'980.000đ', spec:'Bộ 25kg' },
    'G20C':  { price:'650.000đ', spec:'Bộ 20kg' },
    'PU S700':   { price:'2.083.000đ', spec:'Thùng 20kg' },
    'PU S400':   { price:'1.500.000đ', spec:'Thùng 18kg' },
    'Pu Glass':  { price:'2.500.000đ', spec:'Thùng 20kg' },
    'CT0':       { price:'408.000đ', spec:'Lon 5kg' },
    'G10':     { price:'780.000đ', spec:'Thùng 18kg' },
    'Latex S': { price:'271.000đ', spec:'Can 5L' },
    'Walling': { price:'667.000đ', spec:'Can 5L' },
    'Grout G650': { price:'146.000đ', spec:'Bao 25kg' },
    'Repair G50': { price:'271.000đ', spec:'Bao 25kg' },
  },
  sika: {
    'Sika Top 107': { price:'~810.000đ', spec:'Bao 25kg' },
    'Sikalastic 1K': { price:'~2.700.000đ', spec:'Thùng 20kg' },
    'Sika Latex':  { price:'~465.000đ', spec:'Can 5L' },
    'SikaGrout 214': { price:'~280.000đ', spec:'Bao 25kg' },
  },
  kova: {
    'K871 GOLD': { price:'5.020.000đ', spec:'20kg' },
    'K5500 GOLD': { price:'3.888.000đ', spec:'20kg' },
    'K260 GOLD': { price:'1.720.000đ', spec:'20kg' },
    'K360 GOLD': { price:'6.656.000đ', spec:'20kg' },
    'CT04T GOLD': { price:'4.755.000đ', spec:'20kg' },
    'CT-11A GOLD': { price:'4.445.000đ', spec:'20kg' },
    'CT-14 GOLD': { price:'4.210.000đ', spec:'20kg' },
    'MTN GOLD': { price:'855.000đ', spec:'25kg' },
    'CT08 GOLD': { price:'6.760.000đ', spec:'20kg' },
  },
  nippon: {
    'Matex':  { price:'~1.130.000đ', spec:'Thùng 18L' },
    'Weatherbond': { price:'~1.290.000đ', spec:'Thùng 18L' },
  },
  nano: {
    'NO1-15L': { price:'4.983.000đ', spec:'15L' },
    'NO1-5L':  { price:'1.765.000đ', spec:'5L' },
    'NO1-1L':  { price:'418.000đ', spec:'1L' },
    'NO2-18L': { price:'4.818.000đ', spec:'18L' },
    'NO2-5L':  { price:'1.620.000đ', spec:'5L' },
    'NO3-18L': { price:'3.886.000đ', spec:'18L' },
    'NO3-5L':  { price:'1.128.000đ', spec:'5L' },
    'NO4-18L': { price:'2.818.000đ', spec:'18L' },
    'NO4-5L':  { price:'836.000đ', spec:'5L' },
    'NO5-18L': { price:'2.188.000đ', spec:'18L' },
    'NO5-5L':  { price:'720.000đ', spec:'5L' },
    'NO6-18L': { price:'2.458.000đ', spec:'18L' },
    'NO6-5L':  { price:'768.000đ', spec:'5L' },
    'NO7-18L': { price:'1.068.000đ', spec:'18L' },
    'NO7-5L':  { price:'389.000đ', spec:'5L' },
    'NA1-5L':  { price:'2.138.000đ', spec:'5L' },
    'NA1-1L':  { price:'496.000đ', spec:'1L' },
    'NA2-15L': { price:'5.818.000đ', spec:'15L' },
    'NA2-5L':  { price:'1.957.000đ', spec:'5L' },
    'NA2-1L':  { price:'474.000đ', spec:'1L' },
    'NA3-15L': { price:'4.398.000đ', spec:'15L' },
    'NA3-5L':  { price:'1.486.000đ', spec:'5L' },
    'NA4-18L': { price:'2.998.000đ', spec:'18L' },
    'NA4-5L':  { price:'958.000đ', spec:'5L' },
    'NA5-5L':  { price:'1.828.000đ', spec:'5L' },
    'NA5-1L':  { price:'458.000đ', spec:'1L' },
    'NA6-18L': { price:'4.428.000đ', spec:'18L' },
    'NA6-5L':  { price:'1.340.000đ', spec:'5L' },
    'NA7-18L': { price:'5.368.000đ', spec:'18L' },
    'NA7-5L':  { price:'1.566.000đ', spec:'5L' },
    'KT1-18L': { price:'1.605.000đ', spec:'18L' },
    'KT1-5L':  { price:'485.000đ', spec:'5L' },
    'KT2-18L': { price:'2.228.000đ', spec:'18L' },
    'KT2-5L':  { price:'708.000đ', spec:'5L' },
    'KT3-18L': { price:'2.737.000đ', spec:'18L' },
    'KT3-5L':  { price:'868.000đ', spec:'5L' },
    'KN1-18L': { price:'2.838.000đ', spec:'18L' },
    'KN1-5L':  { price:'898.000đ', spec:'5L' },
    'KN2-18L': { price:'3.788.000đ', spec:'18L' },
    'KN2-5L':  { price:'1.132.000đ', spec:'5L' },
    'KN3-18L': { price:'4.508.000đ', spec:'18L' },
    'KN3-5L':  { price:'1.365.000đ', spec:'5L' },
    'B1':      { price:'620.000đ', spec:'40kg' },
    'B2':      { price:'838.000đ', spec:'40kg' },
  },
};

function getPrice(bid, code) {
  const pm = PRICE_MAP[bid];
  if (!pm) return null;
  return pm[code] || null;
}

// Count products
for (const b of BRANDS) {
  const data = PRODUCTS[b.id];
  if (Array.isArray(data)) b.count = data.length;
  else { let c=0; for(const k in data) c+=data[k].length; b.count = c; }
}

const PRICES = [
  // --- MUNICH ---
  { brand:'Munich', product:'G20 - Màng chống thấm đàn hồi 200%', spec:'Bộ 25kg', price:'980.000đ' },
  { brand:'Munich', product:'G20 - Màng chống thấm đàn hồi 200%', spec:'Lon 5kg', price:'270.000đ' },
  { brand:'Munich', product:'G20C - Siêu cứng hiệu ứng lá sen', spec:'Bộ 20kg', price:'650.000đ' },
  { brand:'Munich', product:'PU S700 - Chống thấm PU đàn hồi 700%', spec:'Thùng 20kg', price:'2.083.000đ' },
  { brand:'Munich', product:'PU S700 - Chống thấm PU đàn hồi 700%', spec:'Lon 4kg', price:'525.000đ' },
  { brand:'Munich', product:'PU S400 - Chống thấm PU đàn hồi 400%', spec:'Thùng 18kg', price:'1.500.000đ' },
  { brand:'Munich', product:'AC02 - Chống thấm Acrylic', spec:'Thùng 18kg', price:'1.500.000đ' },
  { brand:'Munich', product:'CT0 - Chống thấm pha xi măng', spec:'Lon 5kg', price:'408.000đ' },
  { brand:'Munich', product:'G10 - Chống thấm gốc Bitum', spec:'Thùng 18kg', price:'780.000đ' },
  { brand:'Munich', product:'PU Glass - Chống thấm PU trong suốt', spec:'Thùng 20kg', price:'2.500.000đ' },
  { brand:'Munich', product:'Latex S - Phụ gia kết nối', spec:'Can 5L', price:'271.000đ' },
  { brand:'Munich', product:'Walling - Chống thấm tinh thể', spec:'Can 5L', price:'667.000đ' },
  { brand:'Munich', product:'Grout G650 - Vữa rót không co ngót', spec:'Bao 25kg', price:'146.000đ' },
  { brand:'Munich', product:'Repair G50 - Vữa sửa chữa bê tông', spec:'Bao 25kg', price:'271.000đ' },
  // --- KOVA ---
  { brand:'Kova', product:'K871 GOLD - Sơn bóng nội thất', spec:'20kg', price:'5.020.000đ' },
  { brand:'Kova', product:'K5500 GOLD - Sơn bóng nội thất', spec:'20kg', price:'3.888.000đ' },
  { brand:'Kova', product:'K260 GOLD - Sơn không bóng nội thất', spec:'20kg', price:'1.720.000đ' },
  { brand:'Kova', product:'K360 GOLD - Sơn bóng ngoại thất', spec:'20kg', price:'6.656.000đ' },
  { brand:'Kova', product:'CT04T GOLD - Trang trí chống thấm', spec:'20kg', price:'4.755.000đ' },
  { brand:'Kova', product:'CT-11A GOLD - Chống thấm', spec:'20kg', price:'4.445.000đ' },
  { brand:'Kova', product:'CT-14 GOLD - Chống thấm giãn', spec:'20kg', price:'4.210.000đ' },
  { brand:'Kova', product:'MTN GOLD - Matit ngoại thất', spec:'25kg', price:'855.000đ' },
  { brand:'Kova', product:'CT08 GOLD - Sơn sân tennis', spec:'20kg', price:'6.760.000đ' },
  // --- DULUX (giá tham khảo thị trường) ---
  { brand:'Dulux', product:'Weathershield Colour Protect - Ngoại thất', spec:'15L', price:'~3.280.000đ' },
  { brand:'Dulux', product:'Inspire - Sơn nội thất', spec:'18L', price:'~2.930.000đ' },
  { brand:'Dulux', product:'5in1 Ambiance - Nội thất cao cấp', spec:'5L', price:'~1.200.000đ' },
  { brand:'Dulux', product:'A1000 Professional - Nội thất', spec:'18L', price:'~2.110.000đ' },
  { brand:'Dulux', product:'Aquatech - Chống thấm', spec:'6kg', price:'~710.000đ' },
  { brand:'Dulux', product:'Bột trét tường', spec:'40kg', price:'~397.000đ' },
  // --- NIPPON (giá tham khảo thị trường) ---
  { brand:'Nippon', product:'Matex - Sơn nội thất', spec:'18L', price:'~1.130.000đ' },
  { brand:'Nippon', product:'Weatherbond - Sơn ngoại thất', spec:'18L', price:'~1.290.000đ' },
  { brand:'Nippon', product:'Weathergard Siêu bóng - Ngoại thất', spec:'5L', price:'~1.400.000đ' },
  { brand:'Nippon', product:'Odour-Less Spot-Less - Nội thất CC', spec:'18L', price:'~4.050.000đ' },
  { brand:'Nippon', product:'WP200 - Chống thấm', spec:'20kg', price:'~2.009.000đ' },
  // --- NANO HOUSE (Giá niêm yết chính hãng 02/02/2026 - Đã bao gồm VAT) ---
  { brand:'Nano House', product:'NO1 - SUPER INTERIOR (siêu bóng nội thất thượng hạng)', spec:'15L', price:'4.983.000đ' },
  { brand:'Nano House', product:'NO1 - SUPER INTERIOR (siêu bóng nội thất thượng hạng)', spec:'5L', price:'1.765.000đ' },
  { brand:'Nano House', product:'NO1 - SUPER INTERIOR (siêu bóng nội thất thượng hạng)', spec:'1L', price:'418.000đ' },
  { brand:'Nano House', product:'NO2 - ECO NANO GUARD (bóng nội thất cao cấp)', spec:'18L', price:'4.818.000đ' },
  { brand:'Nano House', product:'NO2 - ECO NANO GUARD (bóng nội thất cao cấp)', spec:'5L', price:'1.620.000đ' },
  { brand:'Nano House', product:'NO3 - ECO NANO GLOSSY (bóng nội thất cao cấp)', spec:'18L', price:'3.886.000đ' },
  { brand:'Nano House', product:'NO3 - ECO NANO GLOSSY (bóng nội thất cao cấp)', spec:'5L', price:'1.128.000đ' },
  { brand:'Nano House', product:'NO4 - ECO NANO CLEAN (bóng nội thất đặc biệt)', spec:'18L', price:'2.818.000đ' },
  { brand:'Nano House', product:'NO4 - ECO NANO CLEAN (bóng nội thất đặc biệt)', spec:'5L', price:'836.000đ' },
  { brand:'Nano House', product:'NO5 - ECO CLASSIC (mịn nội thất cao cấp)', spec:'18L', price:'2.188.000đ' },
  { brand:'Nano House', product:'NO5 - ECO CLASSIC (mịn nội thất cao cấp)', spec:'5L', price:'720.000đ' },
  { brand:'Nano House', product:'NO6 - ECO SUPER WHITE (siêu trắng trần)', spec:'18L', price:'2.458.000đ' },
  { brand:'Nano House', product:'NO6 - ECO SUPER WHITE (siêu trắng trần)', spec:'5L', price:'768.000đ' },
  { brand:'Nano House', product:'NO7 - ECO REGULAR (nội-ngoại thất đặc biệt)', spec:'18L', price:'1.068.000đ' },
  { brand:'Nano House', product:'NO7 - ECO REGULAR (nội-ngoại thất đặc biệt)', spec:'5L', price:'389.000đ' },
  { brand:'Nano House', product:'NA1 - SUPER EXTERIOR (siêu bóng ngoại thất thượng hạng)', spec:'5L', price:'2.138.000đ' },
  { brand:'Nano House', product:'NA1 - SUPER EXTERIOR (siêu bóng ngoại thất thượng hạng)', spec:'1L', price:'496.000đ' },
  { brand:'Nano House', product:'NA2 - ECO PRIMER EX (siêu bóng ngoại chống nóng)', spec:'15L', price:'5.818.000đ' },
  { brand:'Nano House', product:'NA2 - ECO PRIMER EX (siêu bóng ngoại chống nóng)', spec:'5L', price:'1.957.000đ' },
  { brand:'Nano House', product:'NA2 - ECO PRIMER EX (siêu bóng ngoại chống nóng)', spec:'1L', price:'474.000đ' },
  { brand:'Nano House', product:'NA3 - ECO NANO SHIELD (bóng ngoại thất cao cấp)', spec:'15L', price:'4.398.000đ' },
  { brand:'Nano House', product:'NA3 - ECO NANO SHIELD (bóng ngoại thất cao cấp)', spec:'5L', price:'1.486.000đ' },
  { brand:'Nano House', product:'NA4 - ECO PLATIUM (mịn ngoại thất cao cấp)', spec:'18L', price:'2.998.000đ' },
  { brand:'Nano House', product:'NA4 - ECO PLATIUM (mịn ngoại thất cao cấp)', spec:'5L', price:'958.000đ' },
  { brand:'Nano House', product:'NA5 - ECO CLEAR (siêu bóng ngoại chống nóng, trong suốt)', spec:'5L', price:'1.828.000đ' },
  { brand:'Nano House', product:'NA5 - ECO CLEAR (siêu bóng ngoại chống nóng, trong suốt)', spec:'1L', price:'458.000đ' },
  { brand:'Nano House', product:'NA6 - ECO PROGUARD (chống thấm cao cấp)', spec:'18L', price:'4.428.000đ' },
  { brand:'Nano House', product:'NA6 - ECO PROGUARD (chống thấm cao cấp)', spec:'5L', price:'1.340.000đ' },
  { brand:'Nano House', product:'NA7 - ECO PROGUARD MÀU (chống thấm màu cao cấp)', spec:'18L', price:'5.368.000đ' },
  { brand:'Nano House', product:'NA7 - ECO PROGUARD MÀU (chống thấm màu cao cấp)', spec:'5L', price:'1.566.000đ' },
  { brand:'Nano House', product:'KT1 - ECO SEALER (lót kiềm nội-ngoại thất)', spec:'18L', price:'1.605.000đ' },
  { brand:'Nano House', product:'KT1 - ECO SEALER (lót kiềm nội-ngoại thất)', spec:'5L', price:'485.000đ' },
  { brand:'Nano House', product:'KT2 - ECO SEALER (lót kiềm nội thất đặc biệt)', spec:'18L', price:'2.228.000đ' },
  { brand:'Nano House', product:'KT2 - ECO SEALER (lót kiềm nội thất đặc biệt)', spec:'5L', price:'708.000đ' },
  { brand:'Nano House', product:'KT3 - INTERIOR (lót kiềm nội thất cao cấp)', spec:'18L', price:'2.737.000đ' },
  { brand:'Nano House', product:'KT3 - INTERIOR (lót kiềm nội thất cao cấp)', spec:'5L', price:'868.000đ' },
  { brand:'Nano House', product:'KN1 - EX-MASTER (lót kiềm ngoại thất đặc biệt)', spec:'18L', price:'2.838.000đ' },
  { brand:'Nano House', product:'KN1 - EX-MASTER (lót kiềm ngoại thất đặc biệt)', spec:'5L', price:'898.000đ' },
  { brand:'Nano House', product:'KN2 - EX-TERIOR (lót kiềm ngoại thất cao cấp)', spec:'18L', price:'3.788.000đ' },
  { brand:'Nano House', product:'KN2 - EX-TERIOR (lót kiềm ngoại thất cao cấp)', spec:'5L', price:'1.132.000đ' },
  { brand:'Nano House', product:'KN3 - ECO PRIMER (lót kiềm ngoại thất thượng hạng)', spec:'18L', price:'4.508.000đ' },
  { brand:'Nano House', product:'KN3 - ECO PRIMER (lót kiềm ngoại thất thượng hạng)', spec:'5L', price:'1.365.000đ' },
  { brand:'Nano House', product:'B1 - HOME COAT (bột bả trong/ngoài)', spec:'40kg', price:'620.000đ' },
  { brand:'Nano House', product:'B2 - LEVEN COAT (bột bả chống thấm)', spec:'40kg', price:'838.000đ' },
  // --- SIKA (giá thị trường tham khảo) ---
  { brand:'Sika', product:'Sikalastic 1K - Chống thấm PU', spec:'Thùng 20kg', price:'~2.700.000đ' },
  { brand:'Sika', product:'SikaTop 107 Seal - Chống thấm bảo vệ', spec:'Bộ 25kg', price:'~810.000đ' },
  { brand:'Sika', product:'Sika Latex - Phụ gia chống thấm', spec:'Can 5L', price:'~465.000đ' },
  { brand:'Sika', product:'Sikagrout 214-11 - Vữa rót không co ngót', spec:'Bao 25kg', price:'~280.000đ' },
  { brand:'Sika', product:'Sikaflex 11FC - Keo trám khe', spec:'Ống 600ml', price:'Liên hệ' },
  // --- JOTUN (giá niêm yết tham khảo) ---
  { brand:'Jotun', product:'Jotashield Bền Màu Toàn Diện - Ngoại thất', spec:'15L', price:'~9.545.000đ' },
  { brand:'Jotun', product:'Jotashield Sạch Vượt Trội - Ngoại thất', spec:'15L', price:'~7.355.000đ' },
  { brand:'Jotun', product:'Jotashield Chống Phai Màu - Ngoại thất', spec:'15L', price:'~7.145.000đ' },
  { brand:'Jotun', product:'Jotun Water Guard - Chống thấm', spec:'20kg', price:'~4.170.000đ' },
  { brand:'Jotun', product:'Tough Shield Max - Ngoại thất kinh tế', spec:'17L', price:'~4.950.000đ' },
];
